### ISSUE TITLE
Lefthand Nav menu blocks underlying content

### ISSUE THREAD

**Issue by liz-shinn** [keep-network/keep-core#1273]
In the Chrome browser on a 13-inch MacBook Pro, the underlying content of the main page is behind the navigation panel. It won't allow to scroll all the way over to the left.

<img width="1084" alt="KEEP_Token_Dashboard" src="https://user-images.githubusercontent.com/57226633/72295583-e14f9380-3625-11ea-94bf-a685b6b4c5ae.png">

**Comment by r-czajkowski** [comment]
The bug is related to the obsolete UI and does not appear in the current version of the KEEP token dashboard.
