### ISSUE TITLE
Loading indicator for token dashboard components

### ISSUE THREAD

**Issue by pdyraga** [keep-network/keep-core#1377]
Loading the data and initializing components takes some time. We currently display a simple overlay with `Loading` label. We need to figure out how this should eventually look like.

![Feb-24-2020 12-34-41](https://user-images.githubusercontent.com/4712360/75149489-6c7e7780-5702-11ea-896f-da7b73f22955.gif)

**Comment by liz-shinn** [comment]
Have some updates on this! 

I think we have two situations here. In one corner there's a full page loading spinner for transitioning between full pages. 

And additionally, there's a smaller loading indication for smaller interactions.

**Comment by liz-shinn** [comment]
For the full page load, here's an example of what I mean:
![pageload](https://user-images.githubusercontent.com/57226633/80535276-880a3680-896e-11ea-8bee-31c7e75951e8.gif)

I'd like to do something like this for ours that uses this Keep icon animation:
https://lottiefiles.com/share/syB8hh

**Comment by liz-shinn** [comment]
![Screen-Recording-2020-04-28-at-04 39-PM](https://user-images.githubusercontent.com/57226633/80535503-e505ec80-896e-11ea-9ab7-90e267fda5ee.gif)

Here's a GIF of it ^

**Comment by liz-shinn** [comment]
And how it would be placed within the context of the dApp:

<img width="1439" alt="Image 2020-04-28 at 4 48 05 PM" src="https://user-images.githubusercontent.com/57226633/80536259-1cc16400-8970-11ea-8e1f-59638c3ea9cc.png">

**Comment by liz-shinn** [comment]
Found a good spinner on loading.io that we can use for smaller interactions:

![Ripple-1 4s-200px](https://user-images.githubusercontent.com/57226633/80539478-914ad180-8975-11ea-9169-13f4d7e1aedc.gif)

GitHub won't let me upload an SVG but I do have an SVG version of it too.

**Comment by r-czajkowski** [comment]
@liz-shinn, sometimes one section fetches faster than other. Do you think we can display this KEEP indicator per section? as now is?

**Comment by liz-shinn** [comment]
Yes – if you want to sync on this let me know. I imagined this indicator would be for loading full sections (e.g. if you switch between the Rewards page and the Token Overview page). What is the shortest page load time? Probably don't show it if it's under a certain amount of time. I was going to suggest setting a minimum length for the loading indicator, but if there's too much full page loads it will give the impression that the system is slow.

**Comment by liz-shinn** [comment]
What are the options for setting conditional requirements for showing/not showing this `K` progress indicator? It's better to not show it and have a faster loadtime (will make it appear as if system is faster). Like if the loadtime is shorter than say 0.5 a second I think we could show a skeleton screen instead, like this one from Figma:

![1_veJSvRhHGpovfXQa3S3hhg](https://user-images.githubusercontent.com/57226633/83035859-f858b600-a007-11ea-97d1-399abb8b0b88.gif)

So, potentially –
1. Loadtime longer than .5 a second – show K animated loader
2. Under .5 a second – show skeleton screen

**Comment by liz-shinn** [comment]
Doing some reading on this, and this article on perceived performance / time and [this section suggests](https://www.smashingmagazine.com/2015/09/why-performance-matters-the-perception-of-time/) loading times are perceived like this:

![Why_Perceived_Performance_Matters__Part_1__The_Perception_Of_Time_—_Smashing_Magazine](https://user-images.githubusercontent.com/57226633/83037060-55a13700-a009-11ea-8689-efb3abf2f316.png)

So perhaps it's greater than ~1s it shows the K loading indicator, in the User Flow category.
