### ISSUE TITLE
Global recover

### ISSUE THREAD

**Issue by pdyraga** [keep-network/keep-core#1505]
Right now, in case of any panic, `keep-core` client dies. We should implement a catch-all recover function logging the failure on ERROR level (maybe even FATAL?) and not letting the client exit. All event handlers should continue to work and the client should continue serving relay requests and participating in group selection. The protocol that failed and led to panic should be aborted.

**Comment by dimpar** [comment]
@pdyraga I have a bit of a puzzle here. I've tried to implement [defer-panic-and-recover](https://blog.golang.org/defer-panic-and-recover) but later when I started testing it, I noticed that if I call `panic()` programatically outside the `goroutine` where I put `defer - recover`, it won't catch it. Say in `beacon.go` we have smth like that:
```
relayChain.OnRelayEntryRequested(func(request *event.Request) {
	defer func() {
		if r := recover(); r != nil {
			fmt.Errorf("recovering from panic. [%v]", r)
			return
		}
	}()

	panic("inside of OnRelayEntryRequested") // works, recover() above will catch it.

        // inner panic() of MonitorRelayEntry() will not be caught in recover() above, because of a different goroutine
	go node.MonitorRelayEntry(
			relayChain,
			request.BlockNumber,
			chainConfig,
		)
	})
```

Later, I also found [this thread](https://groups.google.com/forum/#!topic/golang-nuts/-ZE33955Ktk) among others that says there is no catch all runtime errors in one place just like we can in ex. Java. GO is designed differently and I don't think we can recover in one place (ex. somewhere close to main.go) from all the goroutines that we have.

Maybe I can identify a couple of "key" goroutines and cover them with "defer - recover"? But if for some reason we panic in another place, it won't help it. 

We handle errors everywhere I navigate through the code just like GO is designed and recommends. 

What are your thoughts? Or did I simply misunderstand the requirement?

**Comment by pdyraga** [comment]
My hope was that we can install a short-term defers in the main process loop (`beacon.go`) and protect the main client goroutine to panic if we had a panic inside of e.g. `OnRelayEntryRequested` or `OnGroupSelectionStarted` handler goroutines.

What this approach does not take into account is that - as you say - we create more goroutines inside those goroutines which is a usual thing in Go. Given how the codebase evolved I think the safest option we can do is to recommend process monitoring in the stake operator's guide and start the client again on panic.
