### ISSUE TITLE
Hardware wallet integration

### ISSUE THREAD

**Issue by pdyraga** [keep-network/keep-core#1506]
Provide a way to use hardware wallets with KEEP token dashboard.

**Comment by liz-shinn** [comment]
Dropping slides from Figma into here! I researched some dApps (mainly Oasis) to see how they were handling this. I've currently included MetaMask, Ledger (Live and Legacy), Coinbase, and Trezor. 

MetaMask: Should link to the download page in an external window if it's not installed and have a web3 error
Coinbase: Will show a QR code, link to download Coinbase Wallet 
Ledger: Shows Ledger Live and Ledger Legacy and a 'connect' button that I assume looks for something plugged into the USB drive?
Trezor: Links out to an external wizard

**Comment by liz-shinn** [comment]
The far left modal window shows all the options supported, and the other two are links from when you click either Ledger or Coinbase, respectively.

![Image 2020-03-30 at 4 18 27 PM](https://user-images.githubusercontent.com/57226633/77957843-1f159d00-72a2-11ea-8b6c-6ab7dfdc2500.png)

**Comment by liz-shinn** [comment]
Full screen for context (you can see there's an error message that's saying "Please connect a wallet" in the top lefthand corner).

![Image 2020-03-30 at 4 21 38 PM](https://user-images.githubusercontent.com/57226633/77958120-91867d00-72a2-11ea-98ce-0b5c4d5a5977.png)
![Image 2020-03-30 at 4 22 02 PM](https://user-images.githubusercontent.com/57226633/77958150-9ba87b80-72a2-11ea-9a09-a09c032545de.png)

**Comment by liz-shinn** [comment]
I think that the modal should show initially, though, and not require the user to click on the "Please connect to a wallet" link. 

I'm thinking this link would be there for when the user closes out of this modal but still needs to link a wallet.

**Comment by liz-shinn** [comment]
The copy has changed in Figma for most of these, btw. Also, addition of images to the hardware wallet modal flows:

<img width="409" alt="Image 2020-04-07 at 3 22 07 PM" src="https://user-images.githubusercontent.com/57226633/78710668-bb175800-78e3-11ea-90eb-42f1433cf236.png">
<img width="424" alt="Image 2020-04-07 at 3 22 01 PM" src="https://user-images.githubusercontent.com/57226633/78710674-beaadf00-78e3-11ea-9571-0abbec816d8a.png">
