### ISSUE TITLE
Update the client quickstart

### ISSUE THREAD

**Issue by mhluongo** [keep-network/keep-core#1571]
https://github.com/keep-network/keep-core/blob/master/docs/run-random-beacon.adoc seems to depart from the quickstart in a couple places - should we prefer the random beacon doc and deprecate the quickstart, or bring it back in line?

**Comment by sthompson22** [comment]
The QuickStart guide was written for folks with staking bundles prepared by
us in mind.  It was never really meant for mass consumption.  I’m fine
killing it after we stop with the bundling.
