### ISSUE TITLE
Do not publish DKG result with minimal number of supporting signatures

### ISSUE THREAD

**Issue by pdyraga** [keep-network/keep-core#1585]
For a group of 64 members, we need 33 signature shares to generate relay entry. DKG result is accepted if it has 33 supporting signatures. It means that in the worst scenario _[note]_, all 33 group members need to participate in relay entry signing. 

This is risky. When DKG result is not accepted, group members lose their ETH spent on tickets.  If DKG result is accepted and just some few members decide not to participate in threshold signing, the entire group will lose some of their KEEP.

One option is e.g. to require at least 55 signatures on DKG result so that it's accepted. It gives a safety margin of 22 inactive members.

_[note] In practice, the situation could be a little better because there is a chance that although some members do not support the result they may decide to stay in the group and participate in threshold signing because they support the group public key. It happens in a situation when for example there is a disagreement about a few inactive members._

**Comment by eth-r** [comment]
We could use the DKG nofail threshold for this (75%, leaving 25% of the original or 33% of the reduced group as a safety margin). However, we should already be enforcing the 75% rule in the submitted DKG result; even if we only have 51% signatures the group should not be able to contain less than 75% members and thus the absence of a few signers wouldn't be catastrophic as the non-signer members would still be responsible for producing entries.

It would be possible for a colluding 51% adversary to draft unwilling members into the group to make it past the 75% threshold without their signatures, but in such a group the adversary bears 51~66% of the cost of failing to sign, so I don't think this is a massive problem in practice.

**Comment by pdyraga** [comment]
> However, we should already be enforcing the 75% rule in the submitted DKG result; even if we only have 51% signatures the group should not be able to contain less than 75% members and thus the absence of a few signers wouldn't be catastrophic as the non-signer members would still be responsible for producing entries.

I am not following this one. Where do we enforce it, is it somewhere in the off-chain part?

On-chain, when DKG result is submitted, in `DKGResultVerification` library we check whether `signaturesCount >= self.signatureThreshold` and `self.signatureThreshold` is currently set to `33`.

**Comment by eth-r** [comment]
We should be checking that the number of disqualified operators doesn't exceed 25%; I checked and it's true that we aren't performing this check currently. The lines:
```
        require(
            misbehaved.length <= self.groupSize - self.signatureThreshold,
            "Malformed misbehaved bytes"
        );
```
should be:
```
        require(
            misbehaved.length <= (self.groupSize - self.signatureThreshold) / 2,
            "Malformed misbehaved bytes"
        );
````

**Comment by eth-r** [comment]
Or maybe a bit more to return `false` if the result is otherwise okay but the group would fall below the required number, and then reimburse the submitter but not create the group.

**Comment by dimpar** [comment]
>  When DKG result is not accepted, group members lose their ETH spent on tickets. If DKG result is accepted and just some few members decide not to participate in threshold signing, the entire group will lose some of their KEEP.

From the desc. ^ 

> Or maybe a bit more to return false [..] and then reimburse the submitter but not create the group.

If we return `false` from `dkgResultVerification.verify()`, then in `KeepRandomBeaconOperator::submitDkgResult()` we reimburse submitter only. What about other participants, are they losing KEEP in this case?

**Comment by eth-r** [comment]
@dimpar  If we use `false` to denote "successful submission but group not created" then we should reimburse the submitter and do nothing with the other members. They will lose the gas fees of submitting their tickets just as with a failed group selection where no valid result had been submitted within the timeout.

**Comment by pdyraga** [comment]
Why would I submit DKG result that is not going to be accepted? It's net-zero for the operator. Instead of reimbursing operator we can keep the fee and return it back to the pool later - this is how it currently works. We had this conversation a long time ago and we decided to remove `success/failure` flag from DKG result and submit only successful results. I don't think we should change it now, it would be a last-hour change that I think is not bringing us enough value.

`DKGResultVerification.verify` could be probably cleaned up because it does not make sense to return `bool` there.

Regarding 
```
misbehaved.length <= (self.groupSize - self.signatureThreshold) / 2 
<=> 
misbehaved.length <= 15
```

I think we should still check  `signaturesCount` because it means all those clients completed phase 13 of DKG and there is a higher chance they will persist a threshold signer details on disk and later participate in relay entry signing.

The way the client is coded is that every member through the entire DKG consider itself as honest and it will not sign a result indicating that member's misbehaviour. I do agree it makes sense to validate this on-chain, so maybe we should have:

```
// in KeepRandombeaconOperator:
signatureThreshold = groupThreshold + (groupSize - groupThreshold)/2  // 33 + 15 = 48

// in DKGResultVerification:
uint256 nofailThreshold = (self.groupSize - self.signaturesThreshold) // 64 - 48 = 16

require(misbehaved.length < noFailThreshold)        // < 16
require(signaturesCount >= self.signatureThreshold) // >= 48
```


If we keep `require(signaturesCount >= self.signatureThreshold)` check we are safer. It's true `misbehaved.length < noFailThreshold` is validating the same in ideal conditions but for non-ideal conditions, it's possible we can have 33 signatures on that result and we'll create a group in this case if we don't add  `signaturesCount >= self.signatureThreshold` check.

**Comment by eth-r** [comment]
We could make the signature threshold be the 75% required for a nofail, it's a bit more expensive but safe and doesn't require big contract changes.
