### ISSUE TITLE
Relay entry timeout penalty amount

### ISSUE THREAD

**Issue by pdyraga** [keep-network/keep-core#1586]
In Random Beacon docs we say:

> In later versions, penalties for misbehavior can be adjusted to match the severity of the misbehavior. However, initially the penalty for misbehaving in the random beacon will equal the minimum stake required to join a signing group.

There are 3 cases when KEEP tokens are slashed/seized:
- If the beacon group signing key leaked
- If ECDSA keep signing group signed a digest it wasn't requested to sign
- If the beacon group did not produce entry on time

The severity of the misbehavior is very different. In the first two cases, group members had to intentionally collude out-of-band. In the last case, group members could expect some technical difficulties. In all those cases we slash minimum stake of KEEP which can completely eliminate some stakers and does not encourage to stake.

I think we should ease the punishment in the last case, especially for the early days to e.g. 5-10% of the minimum stake.

**Comment by eth-r** [comment]
We could set the timeout punishment to be a constant 10k so it's 1/10 of the minimum stake initially but the minimum stake schedule ultimately catches up (down?) to it.

**Comment by pdyraga** [comment]
It is one of the options but why do we eventually want entry timeout punishment to catch signature fraud or leaked group key punishment? Those types of misbehaviour are unproportional. I would rather say entry timeout punishment should always stay at 10% of signature fraud punishment, maybe even less.

**Comment by eth-r** [comment]
Entry timeout can be used to manipulate the beacon and it's the most realistic attack vector.

From what I understand the beacon's promise to customers is "this will produce an unpredictable pseudorandom number for you and there is X amount of value backing up this promise". `X` is basically `stakeAtRisk * honestThreshold`, so if we reduce the stake at risk to 10% we only have 10% of the security against attacks in general. For example, someone could bribe group members to precalculate the number and then withhold it if it doesn't yield favorable results. If the timeout penalty is reduced to 10% the amount of bribe required for this attack is reduced 10x, significantly impacting the beacon's usability.

For this reason, in the long term we should have timeout/fraud/leak punishments be equal to the maximum per-member stake we have available. In the short term we could have lower penalties to let the network ease in with slightly less risk until issues are hammered out, which would be achieved by a constant 10k penalty amount. However, we could make all penalties a constant 10k and only use the staking contract minimum stake for ticket calculation; this means that early on stakers, particularly small stakers, risk less in general but the penalties are more transparent and consistent.

For practical numbers, with a honest threshold of 33, the discussed penalty amounts result in the following total effective collaterals:

- 100k: 3,300,000 (1/300 of the total supply)
- 10k: 330,000 (1/3,000)
- 10% of 10k: 33,000 (1/30,000)

If we look at token market caps, currently the n.1 (Bitcoin) is roughly $120B, n.2 (Ethereum) is $17B, and n.10 (Tezos) is $1.3B. The respective collateral values for these market caps would be:

- 100k: $396,000,000 / $56,100,000 / $4,290,000
- 10k: $39,600,000 / $5,610,000 / $429,000
- 10% of 10k: $3,960,000 / $561,000 / $42,900

In the 10% of 10k scenario, even a very highly valued KEEP token would only provide security comparable to the price of a fancy car. It is not hard to come up with scenarios where manipulating the output of the random beacon would be worth more than a fancy car. The collateral token would need to be valued absurdly highly before substantial security would be achieved. Using 10k as the collateral amount makes significant levels of security a lot easier to reach without the underlying token having moonlambo valuations, and starting with 100k wouldn't be unreasonable either.

**Comment by mhluongo** [comment]
High level I agree with @eth-r . If we're worried about poorly configured nodes at launch, slowly raising a slashing multiplier from 0.1 to 1.0 would make sense- but lowering the min slashed means the assurances of using the beacon are lowered by the same amount. At launch, a 64 member group will have something like $400k-750k at risk, meaning "lottery" style use cases can protect that much on the outside. Lowering that to $40k is pretty unappetizing

I get that collusion is "worse", but slashing isn't really about what's better or worse, it's about setting economic parameters for trust. In fact, if collusion is attributable I'd be down to take "all the KEEP" and slash to the bone, but IIRC it isn't so we have to stick with minimum stakes

**Comment by pdyraga** [comment]
> In fact, if collusion is attributable I'd be down to take "all the KEEP" and slash to the bone

It is attributable only for ECDSA n-of-n case so we could employ slash to the bone policy there but it's pretty late in the game to make this change. 

Thanks for doing the math @eth-r, it all makes perfect sense. Looking again at the minimum stake schedule, I do agree 10% of a minimum stake does not make sense long-term. 

@mhluongo @eth-r Can we agree to lower relay entry timeout punishment to 10k? This is 10% of the initial minimum stake but 100% of the final value of the minimum stake after 2 years.

Worth noting, for early days, it helps only stakers having more than 100k of KEEP. When someone has 100k of KEEP and gets slashed for 10k, they are removed from the network because they have no minimum stake.

**Comment by eth-r** [comment]
Using a constant 10k for punishments would effectively implement the 0.1 slashing multiplier through the minimum stake schedule without extra code. It'd also ensure that the value of the collateral can't fall if the value of KEEP doesn't rise to match the reduction from the minimum stake schedule. However, the initial collateral would be rather low and while this would make sense from a "don't put too much trust in the numbers given by immature tech" perspective it would limit the usefulness of the early beacon (either a constant or schedule-following punishment amount still relies on KEEP appreciation to have high deterrent later on).
