### ISSUE TITLE
Banner updates for stakedrop

### ISSUE THREAD

**Issue by liz-shinn** [keep-network/keep-core#1590]
Text that's in the banner sections currently is:
on keep: NOTICE: As of 4/10/2020, we have not announced any token sale or air drop of any kind.
on tbtc: tBTC will launch on April 27th, 2020. Read more in Bloomberg.

Would like to update on Keep to read this:
~ANNOUNCING: First stakedrop for tBTC on June 8, 2020. Add to Calendar~
Stake ETH, Earn KEEP: Join us for a live stakedrop event on June 8, 2020! RSVP Here 

The message on tBTC to read this: 
~The first stakedrop for tBTC is on  June 8, 2020. Add to Calendar~
Stake ETH, Earn KEEP: Join us for a live stakedrop event on June 8, 2020. RSVP Here 

Event link: https://www.crowdcast.io/e/keep-stakedrop---live

**Comment by liz-shinn** [comment]
![Keep_Website](https://user-images.githubusercontent.com/57226633/79136083-6ad64500-7d7e-11ea-92b9-b48ee531a6d3.png)

**Comment by liz-shinn** [comment]
![tBTC_Website](https://user-images.githubusercontent.com/57226633/79139780-ed620300-7d84-11ea-8205-aa98c20387fd.png)

**Comment by liz-shinn** [comment]
Attached screenshots above of the copy dropped into the UI.

**Comment by liz-shinn** [comment]
Event link: https://www.crowdcast.io/e/keep-stakedrop---live

**Comment by liz-shinn** [comment]
<img width="744" alt="Keep_Website" src="https://user-images.githubusercontent.com/57226633/79278539-dfda7500-7e79-11ea-983b-2c8330894752.png">

**Comment by ironng** [comment]
PR https://github.com/keep-network/website/pull/167
