### ISSUE TITLE
Operator page UI updates

### ISSUE THREAD

**Issue by r-czajkowski** [keep-network/keep-core#1632]
Let's update the operator page according to [Figma](https://www.figma.com/file/Su61MwHLrQn3ld24q85pMx/Token-Dashboard-dApp?node-id=2540%3A1637) views.

![obraz](https://user-images.githubusercontent.com/57687279/79743473-eb5bef00-8304-11ea-9497-ddf5b66c471f.png)
![obraz](https://user-images.githubusercontent.com/57687279/79743493-f6af1a80-8304-11ea-8c28-39b0c064a401.png)

**Comment by dimpar** [comment]
Also, I think we should hide the text "Click undelegate below..." if all tokens have been already undelegated.
![Screenshot 2020-05-05 at 13 54 15](https://user-images.githubusercontent.com/3156420/81063426-0b300d00-8ed8-11ea-9222-351c592ec5c2.png)
