### ISSUE TITLE
Glossary page in KEEP token dashboard

### ISSUE THREAD

**Issue by r-czajkowski** [keep-network/keep-core#1633]
Let's add a Glossary page according to [Figma view](https://www.figma.com/file/Su61MwHLrQn3ld24q85pMx/Token-Dashboard-dApp?node-id=2741%3A23561)

![obraz](https://user-images.githubusercontent.com/57687279/79743690-4beb2c00-8305-11ea-9085-73bb5b715298.png)

**Comment by liz-shinn** [comment]
This has been updated:

![Glossary](https://user-images.githubusercontent.com/57226633/80542787-ac204480-897b-11ea-8e91-0f8359334ea4.png)

**Comment by liz-shinn** [comment]
The tooltips within the dapp also link to this page. Some examples:

<img width="493" alt="Image 2020-04-28 at 6 09 29 PM" src="https://user-images.githubusercontent.com/57226633/80542860-c9eda980-897b-11ea-8ebf-d89a82c89ea9.png">
