### ISSUE TITLE
Rewards page UI updates in KEEP token dashboard

### ISSUE THREAD

**Issue by r-czajkowski** [keep-network/keep-core#1636]
The rewards page is probably ready. We need to confirm and check if everything is ok.

![obraz](https://user-images.githubusercontent.com/57687279/79745572-d719f100-8308-11ea-871a-a909e3160589.png)

**Comment by r-czajkowski** [comment]
@pdyraga, what do we do with the ETH value in $?

**Comment by liz-shinn** [comment]
Updates to this page addressing the concern for withdrawal by row (for the case where a beneficiary has multiple operators per one signing group), as well as including a potential for withdraw all at the top that has a gas cost estimate:

![beaconrewardspage](https://user-images.githubusercontent.com/57226633/84961029-445fbd80-b0d1-11ea-8651-f4848e36af6f.png)

**Comment by liz-shinn** [comment]
Changing the labels of the rewards to more accurately reflect rewards status vs signing group status:
![rewards status](https://user-images.githubusercontent.com/57226633/85145266-539e5280-b21a-11ea-80b1-b728de9a3c4d.png)
