### ISSUE TITLE
Incorrect contract address

### ISSUE THREAD

**Issue by sl-he** [keep-network/keep-core#1672]
Incorrect contract address here:
https://docs.keep.network/run-random-beacon.html

07:39:08.378 DEBUG keep-block: subscribing to new blocks blockcounter.go:163
07:39:11.258 CRITI  keep-main: error connecting to Ethereum node: [error resolving TokenStaking contract: [configured address [0x0944aace7232c011d5fec456dffce0c639324e5b0] for contract [TokenStaking] is not valid hex address]] main.go:77

**Comment by Shadowfiend** [comment]
This should be resolved :)
