### ISSUE TITLE
Support WalletConnect

### ISSUE THREAD

**Issue by mhluongo** [keep-network/keep-core#1751]
Including Gnosis in our wallet connect UX will allow multisig users to use the dashboard more easily.

https://github.com/gnosis/safe-web3-provider
https://github.com/gnosis/safe-browser-extension

Alternatively, maybe we can use something like [WalletConnect](https://walletconnect.org/apps) to make supporting additional wallets easier? It appears to cover Gnosis Safe

**Comment by H-KE** [comment]
This would be an amazing addition to the keep dashboard, and encourages good practices amongst network participants. Is there a timeline for building such a feature?

**Comment by H-KE** [comment]
My suggestion would be to build a WalletConnect integration. Supporting an agnostic protocol seems preferable to a custom integration.

**Comment by mhluongo** [comment]
Please @H-KE, if you have the bandwidth we'd welcome the contribution!

**Comment by mhluongo** [comment]
@Shadowfiend @r-czajkowski want to share any upfront thoughts that might save @H-KE some time?

**Comment by mhluongo** [comment]
Interested in thoughts here @Battenfield considering some of our other wallet stuff.

**Comment by MarkOSullivan94** [comment]
+1 for Wallet Connect support - it's a shame that I'm missing out on KEEP rewards despite being an ETH-TBTC LP on UniSwap

**Comment by rbcp18** [comment]
+1 for Wallet Connect support!
