### ISSUE TITLE
Dashboard gives an error on delegation.

### ISSUE THREAD

**Issue by prestwich** [keep-network/keep-core#1797]
On delegation, the dashboard gives an error toast notification with the following text:
```gas required exceeds allowance (10000000) or always failing transaction```

The number varies, but is always around 10mm.

**Comment by Shadowfiend** [comment]
💥🍻😬 

Thanks for posting an issue!

Handful of questions:
- Has this account already delegated?
- Is the out-of-gas before or after submitting? (Guessing after as I don't see any failed delegation transactions, but worth checking heh.)
- Is it possible the operator address has already received a delegation? (This should give a clearer error, so if it isn't it's still unexpected.)
- Any chance you could pass along the transaction data for the failing transaction? Can take it via telegram/discord/keybase/email if you're not comfortable posting it here.

**Comment by Shadowfiend** [comment]
Conclusion (reached offline) here was that it was an operator reuse issue. We're going to need to check for that + display a proper error, preferably before hitting Metamask in the first place. May make sense as a field validation. /cc @liz-shinn @r-czajkowski @dimpar
