### ISSUE TITLE
keep-client-quickstart.adoc missing

### ISSUE THREAD

**Issue by nysxah** [keep-network/keep-core#1798]
Hi all. Was looking for instructions on how to run a node.

The `keep-client-quickstart.adoc` linked under "Running a Node" of https://github.com/keep-network/keep-core/blob/master/README.adoc is missing (404s).

> Feedback on this process and the documentation is appreciated!

This is it =)

**Comment by sthompson22** [comment]
We've retired the quickstart in favor of https://github.com/keep-network/keep-core/blob/master/docs/run-random-beacon.adoc .  The readme reflects the new doc link now.  Thanks for reporting!
