### ISSUE TITLE
Bundle or remove dynamic dependencies

### ISSUE THREAD

**Issue by mhluongo** [keep-network/keep-core#18]
As found in #17, dynamic dependencies required by the BLS implementation make builds and end-user deploys a PITA.

In particular, https://github.com/dfinity/go-dfinity-crypto/ depends on https://github.com/dfinity/bn, which is intended to be installed or included pre-built as a dynamic lib.

We need to either get to a single static executable, or package the client up with any dependencies in a platform-specific way for at least macOS and reasonable Debians.

**Comment by Shadowfiend** [comment]
Having lost the dependency on bn and go-dfinity-crypto, this is no longer an issue :tada:
