### ISSUE TITLE
Rewards not Visible on Token Dashboard

### ISSUE THREAD

**Issue by navneetlakra** [keep-network/keep-core#1804]
The rewards are no longer visible on the token dashboard. Used to see the rewards alright till last a few days back.
![image](https://user-images.githubusercontent.com/10936810/82108907-9a111500-9775-11ea-8b50-b2e2c6946dd2.png)

Please let me know if more information is required.

**Comment by r-czajkowski** [comment]
Thanks for reporting! I think it could be related to #1823
