### ISSUE TITLE
Error unclear when trying to delegate to operator address that is already an authorized operator.

### ISSUE THREAD

**Issue by suprnrdy** [keep-network/keep-core#1805]
Error message in contract is unclear why I'm not able to delegate a stake to an operator address: 
"ALERT: Transaction Error. Exception thrown in contract code."

Steps to recreate: 
1) Delegate stake to an operator address
2) Once delegated, attempt to delegate stake again to an authorized operator address

Expected outcome:
A message stating that the operator address has already been authorized.

**Comment by r-czajkowski** [comment]
Ref: #1797

**Comment by r-czajkowski** [comment]
The described situation no longer occurs- it would create a top-up for the existing operator. Also the dapp displays a modal indicating that delegation for a given operator already exists, please see https://github.com/keep-network/keep-core/pull/2434.
