### ISSUE TITLE
Dashboard copy function not working as expected

### ISSUE THREAD

**Issue by suprnrdy** [keep-network/keep-core#1806]
Recreating problem:
Clicking on any of the ETH addresses (wallet/operator/contracts) doesn't copy the address to the clipboard. The UI says copied, but address is not actually copied. This could be a problem if people are working with other ETH addresses and copy without paying attention. 

Expected outcome: When clicking on an ETH address, the copy function copies the address to clipboard

**Comment by r-czajkowski** [comment]
Duplicate of: #1771

Thanks for reporting! I hope this problem has been addressed with #1791.
