### ISSUE TITLE
Adding withdraw button to the bonding section

### ISSUE THREAD

**Issue by dimpar** [keep-network/keep-core#1812]
For this first implementation, it can be a “withdraw all” that goes straight to a Metamask popup and sets the amount as the full unbonded amount. 

The “full” implementation here would be similar to “Add”, in that it lets you specify how much you want to withdraw. We should also notify users that they are withdrawing to the beneficiary address.

**Comment by liz-shinn** [comment]
Working on this in the Figma file here: https://www.figma.com/file/Su61MwHLrQn3ld24q85pMx/Token-Dashboard-dApp?node-id=2172%3A321

**Comment by liz-shinn** [comment]
![add-eth](https://user-images.githubusercontent.com/57226633/82357550-4996f300-99d3-11ea-9638-2f7338805c4f.gif)

This GIF shows adding ETH. Note that the 'Withdraw` button state changes from inactive to active once there is a balance of ETH added.

**Comment by liz-shinn** [comment]
![Withdraw ETH](https://user-images.githubusercontent.com/57226633/82360011-b9f34380-99d6-11ea-87d8-59aabccbeb74.png)


When you click `Withdraw` it pulls up a window like Add ETH does where you can enter an amount. Prominently notes that withdrawn ETH goes to the beneficiary address.

**Comment by liz-shinn** [comment]
**SHORT TERM**
We'll skip the modal for withdrawal and just add a button that reads "Withdraw All" 

Also in the short-term we can bold and change the color of the instructions where it indicates ETH withdrawal goes to the beneficiary address.

![Image 2020-05-19 at 2 12 49 PM](https://user-images.githubusercontent.com/57226633/82362963-2bcd8c00-99db-11ea-9778-f8bb6687ebcf.png)
