### ISSUE TITLE
Consider adding an etherscan link to success banner or make it visible longer

### ISSUE THREAD

**Issue by dimpar** [keep-network/keep-core#1813]
As for now, it takes a while on mainnet before a user can see a success banner which closes a banner with a transaction link. However, it would be nice to give a user control over when he/she wants to close it, giving more time to click on the etherscan link.

see https://github.com/keep-network/keep-core/pull/1794#issuecomment-630161238

**Comment by liz-shinn** [comment]
Makes sense to me. Added to the design file:

<img width="708" alt="Token_Dashboard_dApp" src="https://user-images.githubusercontent.com/57226633/82941433-56cc5880-9f64-11ea-9ea8-70d056fafe13.png">
