### ISSUE TITLE
Styling is off in the bonding section of tBTC

### ISSUE THREAD

**Issue by dimpar** [keep-network/keep-core#1824]
Also visible in [here](https://github.com/keep-network/keep-core/pull/1822#issuecomment-632669437)

![Screenshot 2020-05-22 at 14 50 56](https://user-images.githubusercontent.com/3156420/82676575-eca37300-9c46-11ea-93d2-96b4a9636257.png)

**Comment by liz-shinn** [comment]
@dimpar I'd recommend setting a fixed width for all of these number input fields so that they're not changing in width & it doesn't expand and overlap with the buttons to the righthand side. 

Wouldn't change number of characters allowed in input – would scroll off to the right.
