### ISSUE TITLE
Metrics add node id

### ISSUE THREAD

**Issue by knarz** [keep-network/keep-core#1853]
There's a metrics endpoint in the works in #1850. There are a lot of things that could be added but one that seems so be fairly often requested in discord at the moment is the `node id` as used for libp2p.

**Comment by lukasz-zimnoch** [comment]
Addressed this in #1850. The node id will be displayed in the metrics list obtained from the `/metrics/` endpoint as:

```
libp2p_info{id="XXXXXXXXXXXXXXXX"} 1
```

**Comment by mhluongo** [comment]
Thanks @knarz! Closed by #1850
