### ISSUE TITLE
Set up a Gitbook for design documentation

### ISSUE THREAD

**Issue by liz-shinn** [keep-network/keep-core#1865]
Setting up a GitBook to store Keep design documentation outside of the Keep UI kit that's in Figma, such as best practices for error messaging, empty states, loading spinners, etc.

**Comment by liz-shinn** [comment]
Drafting of the existing Keep design docs pulled out of Figma and now in GitBook (a much better place for doing things like unordered lists – yeesh, Figma is useless for that!)

GitBook is unlisted, but viewable here: https://keep-network.gitbook.io/keep-design-system/

@Gluzman any other design docs that you think would be good to add to this? Maybe the GitHub process as well?

**Comment by Gluzman** [comment]
Looking great. 
Let’s review over zoom sometime soon. 
Would love to also see an atomic approach to the system. From core elements to colors to bigger components. 

We’ll want to duplicate this approach for tbtc as well I imagine.
