### ISSUE TITLE
Add link to a wallet selection page

### ISSUE THREAD

**Issue by dimpar** [keep-network/keep-core#1887]
Add a navigation link to the wallet selection page like in the images below.

![image](https://user-images.githubusercontent.com/3156420/86460002-eb766300-bd27-11ea-8722-94d100ee2b23.png)

![image](https://user-images.githubusercontent.com/3156420/86459751-94708e00-bd27-11ea-98f6-46caf8b90c04.png)

**Comment by r-czajkowski** [comment]
Going to close this issue since the dashboard UI has changed. Pls see #2113.
