### ISSUE TITLE
Changes in Figma

### ISSUE THREAD

**Issue by dimpar** [keep-network/keep-core#1892]
Views in Figma changed. Some of the changes include:

- Total Balance -> Keep Balance
- Eth Balance in Overview
- Added "progress bar" next to % Staked?

**Comment by liz-shinn** [comment]
@dimpar I'm creating some GH issues now for updates from Figma. I can wrap these into those?

**Comment by r-czajkowski** [comment]
I think we can close this issue because our design has changed drastically and it is probably no longer valid.
