### ISSUE TITLE
Update KEEP token dashboard for top-ups

### ISSUE THREAD

**Issue by pdyraga** [keep-network/keep-core#1898]
https://github.com/keep-network/keep-core/pull/1893 introduces the ability for staker to top-up the existing delegation. Adding tokens to existing delegation is a two-step process: first, staker initiates a top-up, locking new KEEPs in the staking contract. Once the initialization period is over, staker (or anyone else) can commit the top-up, increasing operator's stake.

There is one limitation. We expect the same source of tokens for a top-up as used for the initial delegation. If the initial delegation was done from a grant, the same grant has to be used for a top-up to the operator. If the initial delegation was done using owner's liquid tokens, liquid tokens from the same owner are required for a top-up.

An implication of this change is that tokens staked from a grant, undelegated and recovered does no longer come back to the grant contract. Instead, they are deposited in a special escrow contract from which they can be redelegated or withdrawn, according to grant unlocking schedule.

We need to update KEEP token dashboard to reflect this change.

**Comment by pdyraga** [comment]
Another important requirement is that all calls should now go directly to `TokenStaking` contract.

**Comment by liz-shinn** [comment]
Notes from call on this today in Coda 👍 
<img width="659" alt="Screen Shot 2020-07-08 at 11 12 23 AM" src="https://user-images.githubusercontent.com/57226633/86943922-09233e00-c115-11ea-8690-bd3074375e94.png">

**Comment by pdyraga** [comment]
Posting some more thoughts about it. It's absolutely not a complete solution, just something we can iterate on.

For top-ups, we can have the following flow:

In *Delegate Tokens* section, we move the *Operator Address* input to be the first one. For a delegation, everything works just like now. When the user inputs operator address for existing delegation, *Authorizer Address* and *Beneficiary Address* are filled automatically and disabled for editing. *Delegate Stake* button turns into *Initiate Stake Top-Up*. 

Alternatively, in *Delegations* table below we can add another button, next to *Undelegate*, that will initiate a top-up. We need to display some form, so we could take the user to *Delegate Tokens* section with fields pre-filled as proposed earlier.

Initiated top-ups can be displayed in a table below, next to *Delegations* and *Undelegations*. Each initiated top-up needs to have one button, allowing to commit the top-up as soon as the initialization period passes.

If someone wants to add more tokens to an initializing top-up, we can solve it with a modal informing about the fact the timer will reset if they do that.

I am not sure if the proposed solution about form changing its state is not a UX antipattern but what I like about it is that I have information about my grant/tokens on the right side, so it's easy to me to make a decision about how many tokens I want to top-up.

**Comment by pdyraga** [comment]
More thoughts regarding escrow and its implications. In #1883 we work on a bridge allowing existing stakers to use additional liquidity provided by the company by the time they still have their tokens undelegating from the previous version of the staking contract. Once they have their tokens undelegated, they should withdraw them and pay back for the copied staking relationship. From this point, all those stakers will be the owners of staking relationships based on liquid tokens. The implication about the escrow does not affect them.

For people that haven't been staking yet and those who will use their grant stakeahead to stake to another operator, we can try to "hide" all the details about the escrow in JavaScript and do not bother them about it as long as possible:
- when tokens are released, we'll release them both from a `TokenGrant` and `TokenGrantEscrow`.
- when computing *staked*, *released*, *unlocked* tokens, we'll take into account tokens from a `TokenGrant` and from `TokenGrantEscrow`.
- when someone initiates a top-up, we'll first use tokens available in `TokenStakingEscrow`, trying to drain escrow funds to zero and then add more tokens from `TokenGrant`, if needed.

All those actions may require approving multiple transactions. That should be our v1. If we find out stakers are confused or if it's too expensive for them, we can always implement a smart contract batching those operations together.

The only problematic case I see is: someone has X tokens available in grant, and Y tokens available in the escrow and they want to delegate X+Y tokens. Although it's possible to happen, I don't think it's very probable to happen. I want to see if I can solve it on the `TokenStaking` side but if not, I think we can perhaps solve it with some modal explaining what has happened(?)

**Comment by r-czajkowski** [comment]
> Alternatively, in Delegations table below we can add another button, next to Undelegate, that will initiate a top-up. We need to display some form, so we could take the user to Delegate Tokens section with fields pre-filled as proposed earlier.

I like this one. We already have the necessary information to initiate a top-up such as (operator, beneficiary, authorizer) in the row and we can just display the modal/pop-up to type the top-up amount.

**Comment by pdyraga** [comment]
In terms of priorities, I think the order should be:
- UI for copying the stake, please see #1883 and #1906 
- UI for top-ups, and implementation of the "hidden" solution for balances and unlocking tokens
- all the rest

**Comment by pdyraga** [comment]
#1929 should solve the last problematic case - we can stake from escrow / `TokenGrant` and then top-up immediately as many times as needed, without having the staker suffer from the initialization period twice. With that code, I think we can hide all the implementation details and the only disadvantage to the user is that sometimes, multiple transactions will have to be confirmed in MetaMask.

The only thing we are missing now is:
- how to copy stake in the dashboard?
- UI for top-ups

**Comment by liz-shinn** [comment]
<img width="904" alt="draft" src="https://user-images.githubusercontent.com/57226633/88298977-21dd4780-cd02-11ea-845b-696ecdda75ab.png">

Draft here! In the UI, the `Add Keep` button as a row in the Delegation panel is representing what we're calling top ups. Since the user is adding an amount of tokens I think it's clearer to say that in the UI than "top up."
