### ISSUE TITLE
Stake delegation system tests

### ISSUE THREAD

**Issue by pdyraga** [keep-network/keep-core#1899]
Having top-ups implemented we need to execute system tests covering all possible stake delegation scenarios.
Depending on the progress on #1898, tests should be performed using KEEP token dashboard or directly against smart contracts.

- [x] Grantee can delegate a stake
- [x] Managed grantee can delegate a stake
- [x] Owner of liquid tokens can delegate a stake
- [x] Stake delegation can be canceled within the initialization period by a grantee directly on the staking contract, tokens are deposited to the escrow
- [x] Stake delegation can be canceled within the initialization period by a managed grantee directly on the staking contract, tokens are deposited to the escrow
- [x] Stake delegation can be canceled within the initialization period by an operator directly on the staking contract, tokens are returned to the owner's account
- [x] Stake can be undelegated by grantee directly on the staking contract
- [x] Stake can be undelegated by a managed grantee directly on the staking contract
- [x] Stake can be undelegated by liquid tokens owner directly on the staking contract
- [x] Tokens staked from the grant are deposited in the escrow after recovering them from the delegation
- [x] Staked, liquid tokens are sent back to the owner after recovering them from the delegation
- [x] Tokens can be withdrawn from escrow according to grant's unlocking schedule:
  - [x] permissive staking policy
  - [x] adaptive staking policy
- [x] It is possible to top-up existing delegation from tokens deposited in the escrow
- [x] It is possible to top-up existing delegation from tokens from a grant
- [x] It is possible to top-up existing delegation from tokens from a managed grant
- [x] It is possible to top-up existing delegation from liquid tokens
- [x] It is possible to top-up delegation initiated from escrow with tokens from a grant
- [x] It is not possible to delegate from grant to already used operator whose stake has been canceled
- [x] It is not possible to redelegate from the escrow to already used operator whose stake has been canceled
- [x] Tokens deposited in the escrow can be redelegated to a new operator
- [x] Stake redelegated from the escrow can be canceled
- [x] Tokens deposited in the escrow from a redelegated stake can be withdrawn 
- [x] Stake from liquid tokens can be transferred to new staking contract with a bridge:
  - [x] with payback
  - [x] without payback
- [x] Stake from a grant can be transferred to new staking contract with a bridge
  - [x] with payback
  - [x] without payback
- [x] Stake from a managed grant can be transferred to new staking contract with a bridge
  - [x] with payback
  - [x] without payback

(more...)

**Comment by nkuba** [comment]
Scripts executed during testing are located in: https://github.com/keep-network/local-setup/tree/wip-test-staking-bridge/e2e/wip/staking
