### ISSUE TITLE
Dashboard occasionally fails to add ETH 

### ISSUE THREAD

**Issue by ElderOrb** [keep-network/keep-core#1909]
MetaMask - RPC Error: Error: [ethjs-rpc] rpc error with payload {"id":1501589002953,"jsonrpc":"2.0","params":["0xf891820182843b9aca0082ab7f9435a29348640e8e65568d7dccfaf8f7a8146580e6883782dace9d900000a4f340fa010000000000000000000000005c13fa4a1f056b723cea6bbec1b0d9c8eb00c3b629a0d879531632ad30380accedbf090fc8fb0e53c2f70a0be0e58f4f67abd1376447a06a560b13bf4e744edb9b4cc88d000973027a175a22240ee90d2faf68da990484"],"method":"eth_sendRawTransaction"} [object Object] Object

**Comment by ElderOrb** [comment]
If this is expected behavior - more user-friendly message with some explanation would be appreciated

**Comment by Shadowfiend** [comment]
See also metamask/metamask-extension#8975 and metamask/metamask-extension#8483.

**Comment by r-czajkowski** [comment]
I was able to reproduce this scenario. I tested from different perspectives (owner / grantee / operator / authorizer) and everything works. I think this may be a problem with MetaMask. Definitely need more details. If you can post additional info, that would be great. Thanks!

**Comment by r-czajkowski** [comment]
As I posted above I was not able to recreate the described bug. If the bug still occurs with current dashboard feel free to reopen an issue.
