### ISSUE TITLE
Styling off for external links in Applications section

### ISSUE THREAD

**Issue by liz-shinn** [keep-network/keep-core#1948]
In the below instances, the external link icon is being covered by the text: 

<img width="233" alt="Screen Shot 2020-07-29 at 2 46 56 PM" src="https://user-images.githubusercontent.com/57226633/88802042-d10a9a80-d1aa-11ea-9180-22e24b82adb4.png">
<img width="357" alt="Screen Shot 2020-07-29 at 2 46 38 PM" src="https://user-images.githubusercontent.com/57226633/88802036-cf40d700-d1aa-11ea-9ade-1bcacd5c4ce8.png">
<img width="762" alt="Screen Shot 2020-07-29 at 2 46 47 PM" src="https://user-images.githubusercontent.com/57226633/88802039-d0720400-d1aa-11ea-8dee-d8d55343ca9c.png">

**Comment by r-czajkowski** [comment]
hmm weird 🤔 . We addressed this in https://github.com/keep-network/keep-core/pull/1821. Could you please add more details like browser and browser version? I think we are about mainnet version(https://dashboard.keep.network/) which is not up to date with current `master` branch.

**Comment by liz-shinn** [comment]
Closing this! Yup  – I was viewing the mainnet version and this has been fixed in https://dashboard.test.keep.network/
