### ISSUE TITLE
Dashboard: Slashed tokens do not display

### ISSUE THREAD

**Issue by nikgrego** [keep-network/keep-core#1953]
### Description:
I delegated 300k tokens at the start, my nodes are running for about a month. Then i saw that some tokens are gone, i suppose because of Slashing. As for now 4k are disappeared but they are not displayed in Slashed tokens section. Instead delegation amount decreased to 296k by itself. I suppose it is some sort of bug? 

### Environment details:
OS: OS X El Capitan, 10.11.6 (15G22010)
Web Browser: Google Chrome, Version 83.0.4103.116 (Official Build) (64-bit)  
Wallet: Metamask (Chrome extension), Version 8.0.3

### Screenshots
![Скриншот 2020-07-31 12 07 37](https://user-images.githubusercontent.com/66184067/89020391-7d718b80-d327-11ea-8544-3e4e4d383aa9.png)
![Скриншот 2020-07-31 12 07 01](https://user-images.githubusercontent.com/66184067/89020394-7fd3e580-d327-11ea-844c-7d337ae3f54b.png)

**Comment by r-czajkowski** [comment]
Thanks for posting an issue!

I'm pretty sure we've already fixed this bug. Please see https://github.com/keep-network/keep-core/pull/1919.

**Comment by nikgrego** [comment]
> Thanks for posting an issue!
> 
> I'm pretty sure we've already fixed this bug. Please see #1919.

thanks for comment! i've tried to search for already opened issue, but for some reason haven't find this one 👍

**Comment by r-czajkowski** [comment]
I'm 99% sure this bug is the same as #1919 😄

**Comment by liz-shinn** [comment]
@nikgrego Not related directly to the issue you've posted, but I'm curious what screenshotting service you're using here? The full browser screenshots with dropshadow are nice. I'm working on updating the staking documentation and would like to use a style like these for the images.

**Comment by nikgrego** [comment]
Hi @liz-shinn ! It's the built-in Mac screenshot function 😄  Press and hold these keys together: Shift, Command, 4, and Space bar. Then select the window you want to capture. Here is more info: https://support.apple.com/en-us/HT201361

**Comment by liz-shinn** [comment]
*facepalm OH lol ha. Thanks! 🙌

**Comment by nikgrego** [comment]
> *facepalm OH lol ha. Thanks! 🙌 I use CloudApp for screen recordings, etc. but these look nicer for docs.

No prob 👍  I myself have only recently discovered this function, it's pretty comfy.. for gif captures (when you need to show some action) i use chrome extension called "Chrome Capture" https://chrome.google.com/webstore/detail/chrome-capture-screenshot/ggaabchcecdbomdcnbahdfddfikjmphe

**Comment by r-czajkowski** [comment]
Fix in #1919
