### ISSUE TITLE
MetaMask installation popup

### ISSUE THREAD

**Issue by dimpar** [keep-network/keep-core#1956]
Metamask is already installed. When selecting a MM wallet, you can see a popup that will tell you to install MM. It will appear for a couple of seconds and you will be switched to your selected account. It's just a bit annoying to see this popup when you already have MM installed.

<img width="1680" alt="Screenshot 2020-08-03 at 12 14 53" src="https://user-images.githubusercontent.com/3156420/89172628-3aabef80-d583-11ea-8519-587066262007.png">

**Comment by liz-shinn** [comment]
Agreed – is there a way for us to check the browser to see if the extension has already been installed? If so, then we wouldn't show this pop-up and it would just open MetaMask?
