### ISSUE TITLE
Top-up cannot be cancelled note in KEEP token dashboard

### ISSUE THREAD

**Issue by pdyraga** [keep-network/keep-core#1983]
A top-up cannot be cancelled so it's important that the user is very careful with the amount of KEEP tokens added to the stake. The only way to get those tokens back is to undelegate and recover the stake.

Should we employ some UX pattern or at least add a note to the top-up modal being explicit about the fact a top-up cannot be cancelled and the user has to be careful?

**Comment by liz-shinn** [comment]
Yes — I think adding a note to the top up modal is a good call. 

We could add a confirmation interaction here as well, something along the lines of:
"I understand that the amount of KEEP tokens I am adding cannot be edited once submitted as a top up. To retrieve my tokens I will need to undelegate and recover the entire stake delegation."

**Comment by liz-shinn** [comment]
Could we instead offer an option to partially withdraw a delegation, discussing with @Battenfield

**Comment by liz-shinn** [comment]
I propose some updates to this modal series that would adjust how we display current balance, added amount, and final balance. Would also add a note about top up cancellation:

<img width="967" alt="Screen Shot 2021-04-06 at 10 52 50 AM" src="https://user-images.githubusercontent.com/57226633/113730844-3ca3f080-96c6-11eb-8c63-97e26ffb3fd1.png">

**Comment by liz-shinn** [comment]
![Add KEEP 1](https://user-images.githubusercontent.com/57226633/113730941-56453800-96c6-11eb-9fc0-912305ea1f17.png)
![Add KEEP 2](https://user-images.githubusercontent.com/57226633/113730943-56ddce80-96c6-11eb-8a30-0af0a7a439de.png)
![Add KEEP 3](https://user-images.githubusercontent.com/57226633/113730944-56ddce80-96c6-11eb-9aae-d4deab205dda.png)
![Add KEEP 4](https://user-images.githubusercontent.com/57226633/113730945-57766500-96c6-11eb-86ba-3c4a86dbf2d3.png)

@Battenfield
