### ISSUE TITLE
Token dashboard - not showing 2nd time staked keep ?

### ISSUE THREAD

**Issue by chdru** [keep-network/keep-core#1995]
### Description:
I got a token grant of 300k, my ETH account - 0x27D4876C8dD7abF6e40aAC6F9Fe0942e01fBF5cE.
I'm https://dashboard.test.keep.network dashboard. 
Initially I staked 200k (out of the 300k Grant) and here is my Etherscan txn - https://ropsten.etherscan.io/tx/0x6f073fe20ec00905545c49e0d2e9d6164a3c5b3e767a670b889191ef9761d82f - After this 200k staking, the dashboard said i have staked 66%, This looks all good. 
After couple of days, I later staked additional remaining 100k keep. Etherscan txn - 
https://ropsten.etherscan.io/tx/0xeed3e07c171a19f6a0efa0213032f737ff66420610dab6931958a81e5f44ca4b - this is bit funky to me. Token dashboard everywhere still says - I've only staked 66% /200k and not 300k. 
My available keep is also 0 which means the 100k is staked but not showing in dashboard.

screenshots below showing only 200k staked.
![image](https://user-images.githubusercontent.com/68074440/90523758-e2542080-e132-11ea-956d-021d8b09fc3e.png)

![image](https://user-images.githubusercontent.com/68074440/90523849-f8fa7780-e132-11ea-8882-a6fbd199be38.png)

![image](https://user-images.githubusercontent.com/68074440/90524297-850c9f00-e133-11ea-80c4-daaa366c090f.png)

![image](https://user-images.githubusercontent.com/68074440/90524453-b1c0b680-e133-11ea-9f3b-3da135a50f12.png)

Screenshots showing I have no available keep.
![image](https://user-images.githubusercontent.com/68074440/90523479-8db0a580-e132-11ea-9e9d-624ed0b757cc.png)

### Steps to reproduce the behavior:
1. Initially stake 100k to 200k KEEP in token dashboard.
2. Add additional stake of 100k KEEP. 

### Expected behavior:
I expected it to show me that I've 300k (100%) staked in dashboard. 

### Environment details:
OS: Windows 10 Enterprise, 64 bit
Web Browser: Google Chrome, Version 84.0.4147.125 (Official Build) (64-bit)
Wallet: Metamask (Chrome extension), Version 8.0.7

**Comment by pdyraga** [comment]
Thanks for reporting it. I'll transfer this issue to `keep-core`, that's where KEEP token dashboard code lives.

**Comment by r-czajkowski** [comment]
Thanks for posting an issue!

I think you should also commit a top-up. Could you please check if you have any records in the `Available top-ups` on the `Delegate Tokens` page?

![obraz](https://user-images.githubusercontent.com/57687279/88657277-f677a580-d0d1-11ea-912d-c5be935d2c6b.png)

**Comment by chdru** [comment]
yes - I did indeed have the 100k in the topup and after commiting it, it shows the new KEEP stake. this is good.

One suggestion though - it was not clear to me until you pointed it out saying I have to do a `top up` step to complete the staking process. can we have some comment or pop up during staking process to notify the user to do this step. If not, it can get confusing. 

Thanks !

**Comment by r-czajkowski** [comment]
Improved in https://github.com/keep-network/keep-core/pull/2434 and https://github.com/keep-network/keep-core/pull/2307.
