### ISSUE TITLE
Updates to the notification styling for token dashboard

### ISSUE THREAD

**Issue by liz-shinn** [keep-network/keep-core#2000]
Removes the persistent MetaMask (wallet) login notification (will show that information elsewhere). 

<img width="703" alt="Screen Shot 2020-10-15 at 2 08 07 PM" src="https://user-images.githubusercontent.com/57226633/96169299-ed87ba80-0eef-11eb-91a0-d36d0190eb31.png">

Updates the full width banner notifications to be:
1. No longer full width; compactly & succinctly describes issue and include a link where needed
2. Appears pinned to the righthand corner of the page underneath the wallet, if there are multiple they stack vertically
3. Dismissible notification

**Comment by liz-shinn** [comment]
Example from Figma [file](https://www.figma.com/file/Su61MwHLrQn3ld24q85pMx/Token-Dashboard-dApp?node-id=3621%3A16619)

<img width="589" alt="Screen Shot 2020-08-19 at 4 17 35 PM" src="https://user-images.githubusercontent.com/57226633/90646454-83c49a80-e237-11ea-98b4-2fa00551bad5.png">

**Comment by Shadowfiend** [comment]
Hmm… Some questions:
- Do multiple notifications stack vertically or horizontally?
- Do notifications stay if you navigate away from the current page?

**Comment by liz-shinn** [comment]
Ah good point – I imagine they'd stack vertically; so perhaps in that case it actually makes more sense to pin them to the righthand corner of the dashboard underneath wallet info, instead of by the page title.

**Comment by Shadowfiend** [comment]
That makes a lot of sense conceptually as well, since the actions are associated with the wallet. Incidentally I believe this is also how Gnosis does it.

**Comment by liz-shinn** [comment]
Updated the screenshot above so it shows the notifications sliding in from the right, near the wallet.

**Comment by r-czajkowski** [comment]
Do we have other states for this banner? I mean on the screenshot we have a pending state. We need success, error and a kind of an info banner- (when a user triggers the transaction, the banner with `waiting for the transaction confirmation` is displayed)

![obraz](https://user-images.githubusercontent.com/57687279/96139916-a0134980-0eff-11eb-8df4-6e3a82019c21.png)

**Comment by liz-shinn** [comment]
Yup, all of these notifications would be in the same general style. Here's a link to the design system section with the different layout versions of notifications depending on the context: https://www.figma.com/file/ARAMFLMOPal0JewjvlZGhX/Keep-Design-System?node-id=1168%3A80

<img width="768" alt="Screen Shot 2020-10-15 at 2 04 08 PM" src="https://user-images.githubusercontent.com/57226633/96168870-63d7ed00-0eef-11eb-80d1-dc240bf8d201.png">

**Comment by liz-shinn** [comment]
Drafted a few examples of different notification messages, what are some other messages that I can mock up here?

<img width="509" alt="Screen Shot 2020-10-15 at 2 11 11 PM" src="https://user-images.githubusercontent.com/57226633/96169707-9504ed00-0ef0-11eb-9cea-85b7e5364dcd.png">

These are in figma here: https://www.figma.com/file/Su61MwHLrQn3ld24q85pMx/Token-Dashboard-dApp?node-id=2172%3A321

**Comment by r-czajkowski** [comment]
> what are some other messages that I can mock up here?

error message, that's all I need 😄 . Thanks Liz! 🚀

**Comment by liz-shinn** [comment]
Here are some examples of errors: 

<img width="423" alt="Screen Shot 2020-10-15 at 3 07 59 PM" src="https://user-images.githubusercontent.com/57226633/96175002-393e6200-0ef8-11eb-9719-d45a14c73294.png">
