### ISSUE TITLE
Keep dashboard delegations not appearing

### ISSUE THREAD

**Issue by afmsavage** [keep-network/keep-core#2005]
I have tested creating a new delegation from Wallet A to Wallet B and the delegation does not show up under Grant Delegation overview while logged into the dashboard as Wallet B.  I have some wallet addresses that I was using to test on Ropsten for this if you want to take a look.

Created Delegations of 100k each from
0x2eC7947F3ac9AAaa44b53640506CDc9d848D9489 and 0xa78650eB3749e6D6941fb2Cc3dEdaf95dbEac5Ea 
to
0x8B15E34cEA06219114dC8c0912D43a2ABC2B79c7.  I used this address as the Beneficiary address for both delegations.  Should the delegations not show up in this wallet's dashboard?

**Comment by r-czajkowski** [comment]
Hi!

The `Tokens` page shows data from the `owner's` perspective. Also `grantee` in the token dashboard is as `owner`. As `operator`, you can check delegation on the `Operations` page.

**Comment by afmsavage** [comment]
As the grantee only on a delegation, should there be any info in the dashboard under Grant Delegation Overview?  If not, please feel free to close this out.  I was thinking that if you login as only the grantee, you would have access to some information about the delegation.
