### ISSUE TITLE
Partial Undelegate KEEP in dashboard

### ISSUE THREAD

**Issue by chdru** [keep-network/keep-core#2010]
I was trying an undelegate option on my node and by default it undelegated the entire 100% delegated KEEP tokens. 
I think it would be good to have an option to undelegate partially. i.e. in my case, I wanted to undelegate 100k out of 300k. but I did not have that option. 

![image](https://user-images.githubusercontent.com/68074440/90915794-b7bdce00-e3a5-11ea-930b-727eea44cbcb.png)

**Comment by r-czajkowski** [comment]
Hi! Thanks for posting an issue!

There is nothing that we can do on the dashboard side. The `TokenStaking` contract doesn't provide an option to undelegate partially. Please see [`undelegateAt`](https://github.com/keep-network/keep-core/blob/master/solidity/contracts/TokenStaking.sol#L322) function. @pdyraga, could you add more details here?

**Comment by Shadowfiend** [comment]
Yep, @r-czajkowski basically nailed it. There is no way to partially undelegate, as it would introduce all sorts of bookkeeping complexity. A delegation is a complete unit, and must be undelegated all at once.
