### ISSUE TITLE
Explorer mode / Read-only address

### ISSUE THREAD

**Issue by liz-shinn** [keep-network/keep-core#2024]
Ability to view the Keep Token Dapp without needing to connect via metamask/ledger/etc.

Additionally, you can personify a beneficiary and see your rewards, allows for modality.

Benefits of an "explorer" mode:
1. Having that capability evens the playing field. anyone can view anyone's grant info w/ an address – transparency
2. For demo purposes and for trouble shooting / help
3. Cold storage audience who maintains large token grants they may want to view it without connecting a cold wallet
4. Multi sig actually possible (can enter a multi sig address). Can't currently do anything in the UI and has to be all on command line

**Comment by liz-shinn** [comment]
Check out Zapper.fi for example & Zerion

**Comment by mhluongo** [comment]
Plus :100:

This + [WalletConnect](https://github.com/keep-network/keep-core/pull/2340) and we'll be golden on the access side. Note that I believe WalletConnect supports the Gnosis Safe, so adding instructions around that would also improve the lives of us multisig users
