### ISSUE TITLE
Inline banner style

### ISSUE THREAD

**Issue by liz-shinn** [keep-network/keep-core#2080]
Change inline banner style to more align with label style.
![Screen Shot 2020-09-21 at 4 42 43 PM](https://user-images.githubusercontent.com/57226633/93819247-c8d75480-fc5b-11ea-8291-d55466ae53d0.png)

**Comment by Shadowfiend** [comment]
This likewise did not land for 1.4.0. Moving to 1.5.0 milestone, though it'll probably land in a 1.4.1 or 1.4.2.
