### ISSUE TITLE
MetaMask disconnects when you refresh the page

### ISSUE THREAD

**Issue by liz-shinn** [keep-network/keep-core#2081]
Discord user review: 
>When refreshing or clicking the logo on the top left it automatically signs out and requires to re-select signin method. I would prefer to be kept signed in and have a sign-out option.

**Comment by r-czajkowski** [comment]
Regarding
> clicking the logo automatically signs out and

Solved with https://github.com/keep-network/keep-core/pull/2101/commits/a3751a3c6ca9db3f4fce455d9c861a639d2cab3f
