### ISSUE TITLE
Update Undelegate Copy on Keep Dashboard

### ISSUE THREAD

**Issue by clp16** [keep-network/keep-core#2147]
I think the 2 month undelegate time began, right? If so, the copy needs to be updated. 
![Screen Shot 2020-10-30 at 1 39 52 PM](https://user-images.githubusercontent.com/825949/97739460-3fb30900-1ab6-11eb-9908-b69b7a5ffd4f.png)

**Comment by liz-shinn** [comment]
Thanks! @r-czajkowski @Shadowfiend  – I remember talking about this, but fuzzy on specifics. Does it just need to change to: "There is an undelegation period of 2 months"

**Comment by Shadowfiend** [comment]
Yep, that's correct.

**Comment by r-czajkowski** [comment]
Hmm... that's weird because this modal text [isn't hardcoded](https://github.com/keep-network/keep-core/blob/master/solidity/dashboard/src/components/UndelegateStakeButton.jsx#L15). I'm not able to reproduce this scenario with local contracts. I've deployed `TokenStaking` with different `undelegationPeriod` values and the modal text is correct.

**Comment by r-czajkowski** [comment]
Also the `TokenStaking` contract at address [`0x1293a54e160D1cd7075487898d65266081A15458`](https://etherscan.io/address/0x1293a54e160D1cd7075487898d65266081A15458#readContract) returns  `undelegationPeriod` as 2 weeks.

**Comment by pdyraga** [comment]
Both undelegate + recover need to happen within two months from the moment the contract was deployed to recover tokens in 2 weeks.

We deployed TokenStaking (`0x1293a54e160d1cd7075487898d65266081a15458`) at `1599741820 unix = 2020-09-10 12:43pm (UTC)`. To be able to undelegate and recover in 2 weeks, staker would need to complete the recover until `1599741820 + 5184000 = 1604925820 unix = 2020-11-09 12:43pm (UTC)`. In other words, `1604925820 - 1209600 = 1603716220 unix = 2020-10-26 @ 12:43pm (UTC)` was the last moment to trigger undelegation.

We need to fix this in the dApp and I think it's fine to hardcode 2 months there now.

**Comment by r-czajkowski** [comment]
ahh I see! 🤦  I'll update!
