### ISSUE TITLE
Handle connect wallet button on empty state page

### ISSUE THREAD

**Issue by r-czajkowski** [keep-network/keep-core#2169]
Display wallet menu when the user clicks on the `connect wallet` button on any empty state page.

![obraz](https://user-images.githubusercontent.com/57687279/99225150-e05c3500-27e7-11eb-82bb-c98b8c138a7c.png)

**Comment by liz-shinn** [comment]
Also added this to the v1.5 milestone, unless it's blocking work in the v1.4 milestone?

**Comment by r-czajkowski** [comment]
cool cool thanks! Same thing as here #2170, before v.1.4 deploy we need to remove button.
