### ISSUE TITLE
Display KEEP token balance in a wallet menu

### ISSUE THREAD

**Issue by r-czajkowski** [keep-network/keep-core#2170]
![obraz](https://user-images.githubusercontent.com/57687279/99225637-a9d2ea00-27e8-11eb-8d30-fccd9efcfcd4.png)

**Comment by liz-shinn** [comment]
@r-czajkowski I added this to the v1.5 milestone — or does this block work in the current milestone?

**Comment by r-czajkowski** [comment]
I think we can address it in v1.5 but before v1.4 deploy we need to remove this and `disconnect` button.

**Comment by liz-shinn** [comment]
Sounds good about moving displaying the token balance into a future milestone. But why would we remove the `disconnect` button? That's to prevent a hard refresh from disconnecting the wallet, which it currently does.

**Comment by r-czajkowski** [comment]
I mean in current implementation this button does nothing, we need to implement this. Left this button without action trigger due to lots of changes in a single PR and decided it would be better to handle this in a separate PR.

**Comment by liz-shinn** [comment]
Ahhh I see. Ok! I misunderstood what you meant by remove the `disconnect` button. 👍
