### ISSUE TITLE
Pass `MaxGasPrice` and `BalanceAlertThreshold` properties in Gwei

### ISSUE THREAD

**Issue by lukasz-zimnoch** [keep-network/keep-core#2176]
Currently `MaxGasPrice` and `BalanceAlertThreshold` config properties are passed in `wei`. This can be insufficient for bigger values so it will be good to change the unit of these properties to `Gwei`.

**Comment by nkuba** [comment]
We could also define them in the config as strings and handle as `big.Int` in the code.

@pdyraga any peference?

**Comment by pdyraga** [comment]
Should we close this one @lukasz-zimnoch?

**Comment by lukasz-zimnoch** [comment]
Yep I think so.
