### ISSUE TITLE
Adjusting contrast of minimum stake and staking amount available

### ISSUE THREAD

**Issue by liz-shinn** [keep-network/keep-core#2185]
Contrast issues currently with the minimum stake amount and the staking amount available, two key pieces of information for staking. 

- [x] Adjust design to remedy font sizes and color contrast issues.

- [x] Minimum staking schedule indication in tooltip

![unnamed-1](https://user-images.githubusercontent.com/57226633/100896778-fe36c480-348c-11eb-81ed-8228649e74d6.png)

**Comment by liz-shinn** [comment]
Adjusted the design to be the following:

<img width="746" alt="Screen Shot 2020-12-07 at 2 31 22 PM" src="https://user-images.githubusercontent.com/57226633/101396133-e4382000-3898-11eb-8286-e43ffdbbcb83.png">

**Comment by Battenfield** [comment]
One option would be to show the user that the min stake is about to decrease to X amount in Y amount of days. This could be in the tooltip or on the delegation page.

**Comment by Battenfield** [comment]
https://github.com/orgs/keep-network/projects/30#card-56281528
