### ISSUE TITLE
Version number shows as "undefined" in sidebar menu

### ISSUE THREAD

**Issue by liz-shinn** [keep-network/keep-core#2188]
Version number for the token dashboard is showing as "Version undefined" in the menu sidebar instead of `version 1.4`

<img width="218" alt="Screen Shot 2020-12-03 at 1 58 14 PM" src="https://user-images.githubusercontent.com/57226633/101075967-b7ba9600-3570-11eb-96b0-ce1fc4d588af.png">

cc/ @r-czajkowski

**Comment by r-czajkowski** [comment]
omg forgot to add `copy .env * / app /` to dashboard Dockerfile 🤦 will fix in a moment.
