### ISSUE TITLE
Modal bug when user cancels MetaMask connection

### ISSUE THREAD

**Issue by mhluongo** [keep-network/keep-core#2194]
![Screenshot from 2020-12-05 13-37-13](https://user-images.githubusercontent.com/427505/101260574-0b5aea00-36ff-11eb-9d77-a49fefa4864a.png)

**Comment by liz-shinn** [comment]
![Screen Shot 2021-03-02 at 12 43 26 PM](https://user-images.githubusercontent.com/57226633/109690991-eedf1a00-7b54-11eb-8581-271108ebdbaf.png)

Update the modal text so it doesn't read [object object] and instead says "You rejected the connection request in MetaMask. Please close and try again, and click confirm connection in MetaMask window."
