### ISSUE TITLE
On some empty state pages, call to action button Connect Wallet drops below the fold

### ISSUE THREAD

**Issue by liz-shinn** [keep-network/keep-core#2205]
In some instances, the empty state placeholder image pushes the `Connect Wallet` CTA button below the fold. Need to adjust height / size of empty state placeholders so that we can keep the CTA button on screen. Admittedly, I'm using a 13in Mac so my screen is a bit smaller than the average user, but airing on the side of keeping that CTA button on screen is good 👍 

For example, on the Rewards page:
<img width="1154" alt="Screen Shot 2020-12-08 at 2 05 24 PM" src="https://user-images.githubusercontent.com/57226633/101529512-a6053400-395e-11eb-9a33-4db16ddd7de5.png">

Versus on the Earnings page where you can see the button still:
<img width="1228" alt="Screen Shot 2020-12-08 at 2 07 15 PM" src="https://user-images.githubusercontent.com/57226633/101529538-af8e9c00-395e-11eb-81b5-05e767dca770.png">

I checked the other pages, and this only looks like it happens on the Rewards page. All the other pages I still see the CTA button on screen.

**Comment by Shadowfiend** [comment]
Going to pivot this to: for Rewards specifically, let's remove the second row in the preview so that the connect button pulls up above the fold.
