### ISSUE TITLE
Round percentage value to two decimal places in a circular progress bar

### ISSUE THREAD

**Issue by r-czajkowski** [keep-network/keep-core#2243]
Bug:
![obraz](https://user-images.githubusercontent.com/57687279/103204065-c8072c00-48f6-11eb-989e-c7cac6dfde32.png)

**Comment by liz-shinn** [comment]
Yup was also going to post about this one; seeing it here:

<img width="298" alt="Screen Shot 2020-12-28 at 3 29 58 PM" src="https://user-images.githubusercontent.com/57226633/103241567-9e172f00-4921-11eb-85aa-2610fdbb5740.png">
