### ISSUE TITLE
Percent formatting issue on the overview page

### ISSUE THREAD

**Issue by mhluongo** [keep-network/keep-core#2275]
![Screenshot from 2021-01-08 15-49-12](https://user-images.githubusercontent.com/427505/104062850-35556f80-51c9-11eb-8145-9091b0c563f3.png)

After looking in, I got something that looked like this for wallet percents. Capping it to two decimals should suffice :)

**Comment by liz-shinn** [comment]
Yeah this is gnarly. A few other instances: 

<img width="333" alt="Screen Shot 2021-01-08 at 2 23 16 PM" src="https://user-images.githubusercontent.com/57226633/104069709-8d916f00-51d3-11eb-8b60-1ed76ba68fc0.png">


<img width="253" alt="Screen Shot 2021-01-08 at 2 23 34 PM" src="https://user-images.githubusercontent.com/57226633/104069641-89655180-51d3-11eb-91bb-eccb8f9f4dde.png">


<img width="317" alt="Screen Shot 2021-01-08 at 2 23 49 PM" src="https://user-images.githubusercontent.com/57226633/104069533-823e4380-51d3-11eb-90a7-cba0eb2310cd.png">
