### ISSUE TITLE
Tooltip over tBTC + Saddle Dashboard Pool APY still referencing Uniswap

### ISSUE THREAD

**Issue by suprnrdy** [keep-network/keep-core#2298]
Should the price feed for this APY be from SADDLE API not Uniswap?

<img width="412" alt="Screen Shot 2021-01-19 at 2 34 53 PM" src="https://user-images.githubusercontent.com/1414501/105102981-9cdeab00-5a64-11eb-915a-16dc8a7d005e.png">

**Comment by mhluongo** [comment]
Good catch! We left if for expedience but now, it shouldn't say Uniswap

**Comment by r-czajkowski** [comment]
We use the Uniswap subgraph API to fetch the BTC price in USD based on the TBTC/ETH pool. Using BTC price in USD,  we can compute the total Saddle pool value in USD, assuming that every tokenized BTC in pool is worth the same.

**Comment by mhluongo** [comment]
Oh duh, thanks @r-czajkowski!
