### ISSUE TITLE
Keep only pool APY without wallet connected different than with

### ISSUE THREAD

**Issue by nahuus123** [keep-network/keep-core#2404]
Without a wallet being connected the pool APY that is displayed is different than with a wallet connected. 

It doesn't matter which wallet is connected, in all cases it goes from ~5% to ~10%.

Without:
![image](https://user-images.githubusercontent.com/71384922/113098985-863d9880-91f9-11eb-88e9-58a68cb91d04.png)

With 
![image](https://user-images.githubusercontent.com/71384922/113099014-935a8780-91f9-11eb-8cb4-caa5a51e9baa.png)

**Comment by r-czajkowski** [comment]
Hi! thanks for reporting an issue! 

I was not able to recreate this bug locally and on mainnet. Could you please double-check with the current dashboard at https://dashboard.keep.network/liquidity?

**Comment by nahuus123** [comment]
Hi RC, 

I believe it was fixed in #2425. At least I'm not able to recreate it myself anymore as well.

**Comment by r-czajkowski** [comment]
Perfect! Thanks!

Closing this issue since we are not able to recreate described bug- fixed in #2425.
