### ISSUE TITLE
Dashboard shows random beacon rewards @ 908k

### ISSUE THREAD

**Issue by john-packel** [keep-network/keep-core#2433]
My beacon rewards had been showing ~38k for months, and then I noticed last week that it showed 908k. Before getting too excited I checked discord and saw there was an issue and others were seeing the same thing. 

Then Piotr posted that the issue was fixed, but I'm still seeing 908k. I pinged him and he suggested logging an issue here. 

https://discord.com/channels/590951101600235531/590951101600235533/831595452889038848

Let me know if I can help by testing something. 

- John
<img width="1214" alt="Screen Shot 2021-04-22 at 10 31 49 PM" src="https://user-images.githubusercontent.com/19581802/115809925-07341e00-a3bb-11eb-8941-2eb54b2f0506.png">

**Comment by r-czajkowski** [comment]
Thanks for reporting an issue!

We have already fixed this bug in #2421. It will be released with the next dashboard version.
