### ISSUE TITLE
Keep Dashboard broken links

### ISSUE THREAD

**Issue by david-is-back** [keep-network/keep-core#2454]
On the Liquidity tab the links that point to Uniswap are broken due to their update  from v2 to v3.

**5 links affected:**

2 on KEEP+ETH
1 on KEEP+TBTC
2 on TBTC+ETH

**Comment by mhluongo** [comment]
Here's the new (KEEP/ETH Uniswap link](https://v2.info.uniswap.org/pair/0xe6f19dab7d43317344282f803f8e8d240708174a), for example: `https://v2.info.uniswap.org/pair/0xe6f19dab7d43317344282f803f8e8d240708174a`
