### ISSUE TITLE
Dashboard Liquidity section TBTC + ETH pool APY

### ISSUE THREAD

**Issue by Naxsun** [keep-network/keep-core#2669]
The rewards for the TBTC + ETH pool were voted to stop on October 7th 2021. The last pool top-up with KEEP was made on October 1st 2021.
https://etherscan.io/tx/0xe5b6f069e6cbc1da6c6a0a8210e03b0b64e410f2fd9428682f51e83df42114cc

These rewards were distributed over a week time-frame, so should have been depleted October 8th.  However, the current pool APY is still displayed as 49%.

![image](https://user-images.githubusercontent.com/71384922/138594430-094af540-fc58-4a2c-aafe-6be1c7db9156.png)

**Comment by Naxsun** [comment]
@r-czajkowski in my dashboard it still shows APY >999% and no text as for the others 

"Incentives removed
The incentives for this pool has been removed and you can no longer deposit the lp tokens. You can still withdraw rewards that you already earned."

**Comment by r-czajkowski** [comment]
> @r-czajkowski in my dashboard it still shows APY >999% and no text as for the others
> 
> "Incentives removed The incentives for this pool has been removed and you can no longer deposit the lp tokens. You can still withdraw rewards that you already earned."

We closed the ticket because the changes from https://github.com/keep-network/keep-core/pull/2701 have been merged to `main` branch. The new version of dashboard will be released soon.
