### ISSUE TITLE
Adjust Random Beacon DKG after the changes in ECDSA DKG

### ISSUE THREAD

**Issue by pdyraga** [keep-network/keep-core#2816]
The following changes were applied when working on ECDSA DKG. We need to adjust the Random Beacon DKG and align implementations:
- ECDSA library emits the entire DKG result in `DkgResultSubmitted`
- ECDSA library registers the group only when DKG result was accepted
- ECDSA library does not transfer T rewards for submitting DKG result or unlocking the pool. Instead, ETH reimbursement should be done. See https://github.com/keep-network/tbtc-v2/pull/115
- ECDSA library wraps a calls to `TokenStaking.seize` in a try-catch when challenging the result,

Additionally we need to prefix duplicated contract names (`DKG` -> `BeaconDkg`, `DKGValidator` -> `BeaconDkgValidator`).

**Comment by nkuba** [comment]
> ECDSA library does not transfer T rewards for submitting DKG result or unlocking the pool. Instead, ETH reimbursement should be done. See
https://github.com/keep-network/tbtc-v2/pull/115

What should we do about relay entry submission? Do we want to change the approach there as well to quit tracking submission eligibility?

**Comment by pdyraga** [comment]
> > ECDSA library does not transfer T rewards for submitting DKG result or unlocking the pool. Instead, ETH reimbursement should be done. See
> > [keep-network/tbtc-v2#115](https://github.com/keep-network/tbtc-v2/pull/115)
> 
> What should we do with relay entry submission? Do we want to change the approach there as well to quit tracking submission eligibility?

I do not think we track submission eligibility for relay entries. We should not track it for DKG, both for beacon and ECDSA.

**Comment by nkuba** [comment]
> > > ECDSA library does not transfer T rewards for submitting DKG result or unlocking the pool. Instead, ETH reimbursement should be done. See
> > > [keep-network/tbtc-v2#115](https://github.com/keep-network/tbtc-v2/pull/115)
> > 
> > 
> > What should we do with relay entry submission? Do we want to change the approach there as well to quit tracking submission eligibility?
> 
> I do not think we track submission eligibility for relay entries. We should not track it for DKG, both for beacon and ECDSA.

In `Relay` contract we have the approach where we calculate timeout based on the `groupSize * relayEntrySubmissionEligibilityDelay`. We should make it consistent with DKG and introduce a submission timeout property instead of the multiplication.
