### ISSUE TITLE
ETH refunds - ECDSA and random beacon

### ISSUE THREAD

**Issue by pdyraga** [keep-network/keep-core#2824]
# Overview 

This issue aims at implementing reimbursements for random beacon and ECDSA operator contracts, including implementing the reimbursement ETH pool, as proposed in https://github.com/keep-network/tbtc-v2/pull/115.

Please treat the idea presented here as just a proposition as the reality may require some adjustments.

# Reimbursements

## Random Beacon

| Function                           | ETH reimbursed? | Slashing? | Can anyone call? |
|------------------------------------|-----------------|-----------|------------------|
| submitDkgResult + approveDkgResult | Yes             | No        | No               |
| notifyDkgTimeout                   | Yes             | No        | Yes              |
| submitRelayEntry                   | Yes             | No        | In practice, No  |
| notifyFailedHeartbeat              | Yes             | No        | Yes              |
| challengeDkgResult                 | No              | Yes       | Yes              |
| reportRelayEntryTimeout            | No              | Yes       | Yes              |
| reportUnauthorizedSigning          | No              | Yes       | Yes              |

## ECDSA

| Function                           | ETH reimbursed? | Slashing? | Can anyone call? |
|------------------------------------|-----------------|-----------|------------------|
| submitDkgResult + approveDkgResult | Yes             | No        | No               |
| notifyDkgTimeout                   | Yes             | No        | Yes              |
| notifySeedTimeout                  | Yes             | No        | Yes              |
| challengeDkgResult                 | No              | Yes       | Yes              |

# Smart contracts

## Reimbursement Pool

Although it would be nice to have separate bookkeeping per application, we want the mechanism to be as cheap as possible and not require a lot of operational work. `ReimbursementPool` will be a single contract holding ETH received from the DAO, managing the gas price ceiling, and authorization of contracts eligible to use that ETH for reimbursements. It should also allow the DAO to pull ETH in case an upgrade is needed. This contract will be located in `keep-core`.

```
contract ReimbursementPool is Ownable {
  /// @notice Static gas cost of submitting a TX.
  uint256 staticGasCost;

  /// @notice Max refundable gas price. Protects against malicious
  ///         operator-miners.
  uint256 maxGasPrice;

  modifier onlyAuthorized {
    require(isAuthorized[msg.sender], "Not authorized for a refund");
  }

  function refund(uint256 gasSpent, address spender) external onlyAuthorized {
    // add constant 
  }

  function authorize(address _contract) external onlyOwner {
    isAuthorized[_contract] = true;
  }

  function deauthorize(address _contract) external onlyOwner {
    isAuthorized[_contract] = false;
  }

  function setStaticGasCost(uint256 _staticGasCost) external onlyOwner {
    staticGasCost = _staticGasCost;
  }

  function setMaxGasPrice(uin256 _maxGasPrice) external onlyOwner {
    maxGasPrice = _maxGasPrice;
  }

  function withdraw(uint256 amount, address recipient) external onlyOwner {
    // (...)
  }
}
```

## Code for Reimbursable contracts

`Reimbursable` should encapsulate logic common for all contracts reimbursing function calls. It should allow to update `ReimbursementPool` and to disable reimbursements completely. It also contains the logic for the very basic reimbursement case: single function call.

```
abstract contract Reimbursable is Ownable {

  ReimbursementPool reimbursementPool;
  
  modifier refundable {
    uint256 gasStart = gasleft();
    _;
    uint256 gasEnd = gasleft();
    reimbursement.refund(gasStart - gasEnd);
  }

  function refund(uint256 gasSpent) {
    if (address(reimbursementPool) != address(0x0)) {
      reimbursementPool.refund(gasSpent, msg.sender);
    }
  }

  function setReimbursementPool(ReimbursementPool _reimbursementPool) onlyOwner {
    reimbursementPool = _reimbursementPool;
  }
}
```

## Operator contracts

`RandomBeacon` and `WalletRegistry` operator contracts should inherit from `Reimbursable` and use `refundable` modifier for single-function-call functionalities reimbursing gas costs. Custom logic will be needed for more complex cases, such as submit&approve DKG result where we want to reimburse on everything but only when the result is approved.

```

RandomBeacon is Reimbursable {

  function submitRelayEntry(bytes calldata entry) external refundable {
    // (...)
  }

  function notifyDkgTimeout() external refundable {
    // (...)
  }

  function submitDkgResult(DKG.Result calldata dkgResult) external {
    uint256 gasStart = gasleft();

    // (...)

    uint256 gasEnd = gasleft();

    // capture gasEnd - gasStart 
    // consider there is a static cost of capturing
  }

  function approveDkgResult(DKG.Result calldata dkgResult) external {
    uint256 gasStart = gasleft();

    // (...)

    uint256 gasEnd = gasleft();

    refund(gasStart - gasEnd + submitGasSpent);
  }
}
```

`RandomBeacon` contract will need additional adjustments. `fundDkgRewardsPool`, `fundHeartbeatNotifierRewardsPool`, `transferDkgRewards` and `transferHeartbeatNotifierRewards` functions does no longer make sense. Same about T fee that was used when requesting for entries.

Instead, we want to be able to authorize certain contracts to request for relay entries for free (`WalletRegistry`) and have all other contracts being able to request as well but to provide a fee in ETH. The provided fee should go straight to `ReimbursementPool` contract. 

# Do not reimburse too much

A crucial point of the implementation is to not reimburse too much to do not make function calls attractive for frontrunners. That is, we want to reimburse the exact cost but we do not want anyone to profit on frontrunning.

**Comment by michalinacienciala** [comment]
> @pdyraga, @nkuba, regarding reimbursing for notifyFailedHeartbeat in Random Beacon:
>
> Here we say that the transaction will be reimbursed from the reimbursement ETH pool.
>
> In [random-beacon/README.adoc](https://github.com/keep-network/keep-core/blob/7655b4e85b8fbff148cdc4138feba4346f96f03d/solidity/random-beacon/README.adoc#heartbeats) we say that "The submitter of the failed heartbeat claim receives a reward from a separate notifier reward pool, funded by DAO for heartbeat failure claims specifically. This pool is expected to be funded by DAO with tokens saved from sortition pool rewards as a result of having operators marked as ineligible for rewards due to failing a heartbeat.
> 
> And in [RandomBeacon.sol](https://github.com/keep-network/keep-core/blob/7655b4e85b8fbff148cdc4138feba4346f96f03d/solidity/random-beacon/contracts/RandomBeacon.sol#L342) we set ineligibleOperatorNotifierReward to 0.
>
> So does that mean that we will be reimbursing the cost of sending the notifyFailedHeartbeat transaction from the reimbursement pool, but we leave an open door for additionally rewarding heartbeat notifiers from a separate pool if governance decides to change the value of ineligibleOperatorNotifierReward from 0?
Should we already have that hartbeat-failure specific pool implemented and collecting the un-used rewards?

OK, after discussing with the team I see that what we currently have in the [RandomBeacon.sol](https://github.com/keep-network/keep-core/blob/7655b4e85b8fbff148cdc4138feba4346f96f03d/solidity/random-beacon/contracts/RandomBeacon.sol#L342) is not jet adjusted to the latest idea of how incentives would work in Random Beacon.  Ultimately the approved maintainers sending notification about ineligible operators will be reimbursed for the cost of used gas and there will be no separate reward for sending this tx. So what is written in this Issue is correct, and what we have in the Random Beacon contract and README needs to be updated at some point.

**Comment by michalinacienciala** [comment]
It would be good to include notifyRedemptionTimeout on the list as well.

**Comment by michalinacienciala** [comment]
> It would be good to include notifyRedemptionTimeout on the list as well.

Also, calling a function informing about intention to close a wallet will be reimbursable, we could add that to the issue description as well.
