### ISSUE TITLE
Fix gas reporter for beacon and ecdsa

### ISSUE THREAD

**Issue by pdyraga** [keep-network/keep-core#2955]
Hardhat gas reporter plugin report is empty for `beacon` and `ecdsa` modules.

For `ecdsa` it was fixed in https://github.com/keep-network/keep-core/pull/2944 but because of some other change, it stopped working again. I *think* the reason could be something around https://github.com/threshold-network/solidity-contracts/pull/92 or other change in `@threshold-network/solidity-contracts` deployment scripts because it stopped working after updating `@threshold-network/solidity-contracts` dependency from `">1.1.0-dev <1.1.0-ropsten"` to `">1.2.0-dev <1.2.0-ropsten"` in #2942.

For `beacon`, gas reporter starts working after commenting out `task(TASK_TEST, "Runs mocha tests").setAction` in `hardhat.config.ts` but the root cause is probably somewhere else, and this is just a manifestation.

**Comment by nkuba** [comment]
The problems are caused by a bug in the gas reporter plugin, please see https://github.com/cgewecke/hardhat-gas-reporter/issues/86#issuecomment-1114700353 for more details.
