### ISSUE TITLE
Investigate possible another workaround for hardhat-gas-reporter bug

### ISSUE THREAD

**Issue by nkuba** [keep-network/keep-core#2979]
Refs https://github.com/keep-network/keep-core/issues/2955

In https://github.com/keep-network/keep-core/pull/2970 we introduced a workaround for a bug https://github.com/cgewecke/hardhat-gas-reporter/issues/86.

It turned out that such a  workaround is not necessary in `tbtc-v2` repository. The difference is that in `tbtc-v2` we dont use `--deploy-fixture` flag for hardhat and we load a global fixture `await deployments.fixture()` instead of e.g. `await deployments.fixture("WalletRegistry)`.

This may be a solution we can use in all projects that have problems with the gas reporter.

**Comment by pdyraga** [comment]
@nkuba Can we close this issue now?

**Comment by nkuba** [comment]
Closed by https://github.com/keep-network/keep-core/pull/2980
