### ISSUE TITLE
Regenerate contract bindings

### ISSUE THREAD

**Issue by pdyraga** [keep-network/keep-core#3005]
We need to regenerate smart contract bindings in [`pkg/chain/gen`](https://github.com/keep-network/keep-core/tree/main/pkg/chain/gen) to include v2 smart contracts:
- Threshold Network `TokenStaking`
- `SortitionPool`
- `RandomBeacon`
- `WalletRegistry`
-  TBTCv2 `Bridge`

Part of this work requires finding a workaround to get rid of the old v1 contracts without breaking the build. One potential option could be to replace `ethereum.go` implementation with a fake one.

Dependencies and Makefiles need to be updated to make `go generate` use the v2 code.

**Comment by nkuba** [comment]
Right now we generate ABIs for contracts in the [go bindings generator with `solc`](https://github.com/keep-network/keep-core/blob/2966277e6fe24cb2348d1d00d3fb1327482e796e/pkg/chain/v2/common/Makefile#L30-L31). What if we do the ABIs generation with hardhat in the contracts project and expose the ABI files in the package to be consumed by the Go generator?

**Comment by nkuba** [comment]
@pdyraga do we want to add the `MaintainerProxy` to the list? It was suggested by @dimpar in https://github.com/keep-network/keep-core/pull/3016#issuecomment-1167283716.
