### ISSUE TITLE
Make Random Beacon test use contracts from deployment scripts

### ISSUE THREAD

**Issue by nkuba** [keep-network/keep-core#3017]
Currently, in the RandomBeacon we deploy contracts for test fixtures with ethers. In other projects, we use in tests the contracts that were deployed with hardhat deployment scripts. We need to update Random Beacon's tests to do the same as we do e.g. in ECDSA: https://github.com/keep-network/keep-core/blob/82cfa9e8305f46fc443cc4054111caf9f991529f/solidity/ecdsa/test/fixtures/index.ts#L67-L82

**Comment by dimpar** [comment]
Tests were updated in the following PR https://github.com/keep-network/keep-core/pull/3018
