### ISSUE TITLE
ECDSA DKG test loop

### ISSUE THREAD

**Issue by pdyraga** [keep-network/keep-core#3041]
Depends on #3014 

The client should perform threshold ECDSA DKG every 100 Ethereum blocks and store the result on disk. It should not submit the result to the chain. This is a test loop for the early milestone. The logic should include retry algorithm from #3014.

**Comment by lukasz-zimnoch** [comment]
One thing to improve: https://github.com/keep-network/keep-core/pull/3112#discussion_r941209134

**Comment by lukasz-zimnoch** [comment]
Integration between PRs that must be addressed before closing this issue:
- https://github.com/keep-network/keep-core/pull/3120#discussion_r951203237
