### ISSUE TITLE
Geth node synchronization monitoring

### ISSUE THREAD

**Issue by nkuba** [keep-network/keep-core#3145]
This issue is a continuation of https://github.com/keep-network/keep-core/issues/3012

We should monitor our geth instance synchronization with the chain. First, we should verify if the metrics exposed by the `geth` client suit our needs.

Another solution could be comparing the latest block (`ethereum_latest_block_number`) with the latest block numbers returned from public APIs like Alchemy, Infura, or Etherscan.

**Comment by pdyraga** [comment]
Let's stick to external providers for now. To run our own Goerli node after the merge, we'd have to set up Prysm as well.
