### ISSUE TITLE
Mainnet: Monitoring dashboards for Keep nodes

### ISSUE THREAD

**Issue by pdyraga** [keep-network/keep-core#3348]
The solution should be based on #3279 and should include:
- automated node discovery
- the number of TSS pre-parameters generated
- number of connected peers
- number of connected bootstrap nodes
- uptime
- client version

- [x] Prometheus should persist collected data for 1 year
- [x] The dashboard should be exposed publicly. This may require installing additional Grafana plugins.

**Comment by nkuba** [comment]
Closed by https://github.com/keep-network/keep-core/pull/3375
