### ISSUE TITLE
2023-01-13 testnet release

### ISSUE THREAD

**Issue by michalinacienciala** [keep-network/keep-core#3472]
As a preparation for a new mainnet release, we need to conduct an internal testnet release of the client.

# Checklist:
## 2023-01-13
- [ ] Deploy `random-beacon`, `ecdsa`, `tbtc-v2` contracts on Goerli
- [ ] Modify governance parameters to allow for executing DKG multiple time a day (@lukasz-zimnoch / @tomaszslabon)
- [ ] Build & publish a new client image to internal repository.
- [ ] Update Keep GCP testnet clients.
- [ ] Update documentation of contract addresses: https://docs.threshold.network/extras/contract-addresses/goerli-testnet
- [ ] Update Coda deployment documentation: https://coda.io/d/Building-Keep_d-fmEgBNFVH/Deploy-on-Goerli-checklist_suc3g#_luy45
- [ ] Monitor testnet logs, report all problems.

## 2023-01-16 (?)
- [ ] Update bundles for Staking Providers (@nkuba)
- [ ] Publish new client image to public testnet client build repository (@nkuba)
- [ ] P2P.org testnet clients updated
- [ ] Staked testnet clients updated (?)
- [ ] Boar.network testnet clients updated
- [ ] Vict0r notified about the need for a client upgrade

**Comment by pdyraga** [comment]
@michalinacienciala We have #3401 as a v2.0.0-m2 all-testnet releases bag, I've moved these points to that PR. I have also marked staking provider updates as nice-to-haves - but not must-haves for the user acceptance criteria tests to start. We should start as soon as possible, let's not block on their updates. Closing in favor or #3401.
