### ISSUE TITLE
Difficulty relay maintainer testnet deployment

### ISSUE THREAD

**Issue by pdyraga** [keep-network/keep-core#3533]
We discussed with @tomaszslabon today that testing the difficulty relay maintainer is quite complicated and requires a special path.

Most importantly, on the Keep testnet environment (backed by Bitcoin testnet and Goerli) we use a stubbed difficulty relay contract for tBTC `Bridge`. That stubbed difficulty relay contract always returns 1. The difficulty on Bitcoin testnet may drop to 1 and the retarget rules valid for Bitcoin mainnet and enforced in the `LightRelay` contract sometimes do not apply to Bitcoin testnet. 

At the same time, we have a separate Goerli deployment of the `LightRelay` contract initialized with Bitcoin mainnet data. The difficulty relay maintainer bot deployed in our test cluster uses Bitcoin mainnet data and pushes them to the `LightRelay` contract on Goerli.

The `LightRelay` [is currently not getting deployed on Goerli](https://github.com/keep-network/tbtc-v2/blob/328c7f8d3025b97e461a590e81fa6bb494daa2f8/solidity/deploy/01_deploy_light_relay.ts#L8-L17) and deploying it there automatically would require some major investment. We would need to authorize it in the `ReimbursementPool`, fund the reimbursement pool, and still deploy the stubbed difficulty relay contract used by tBTC `Bridge`.

For the time being, we decided to manually deploy `LightRelay`, `LightRelayMaintainerProxy`, and `ReimbursementPool` and point the relay maintainer bot to those contract passing the address. This trio will be separated from the rest of the testnet deployment. `Bridge` and other tBTC v2 contracts will not interact with them. 

To ease further testing, I propose we introduce a single deployment script for the relay, say `keep-network/tbtc-v2/tree/main/solidity/deploy/999_bitcoin_test_relay.ts` and thoroughly document in the header of this file what is the reasoning behind it. That script would deploy the contract trio, the difficulty relay deployment would be later pointed to.

This issue aims at:
- [ ] Implementing the test setup for the relay
- [ ] Testing the relay and ensuring it is ready to go for mainnet

**Comment by Hotspot00** [comment]
[Uploading audit-binance-tss-lib-final-20191018.pdf…]()

**Comment by pdyraga** [comment]
@tomaszslabon Can we close this PR given #3511 and later #3557 were both merged?
