### ISSUE TITLE
Rename `--goerli` flag to `--testnet` flag, remove `--mainnet` flag

### ISSUE THREAD

**Issue by pdyraga** [keep-network/keep-core#3579]
See [this](https://github.com/keep-network/keep-core/pull/3576#discussion_r1198874503) discussion.

As someone not that familiar with the client code, I would be confused about `--goerli` flag.  This flag clearly connects the client to Goerli Ethereum testnet, but how would I select the Bitcoin testnet? 

Eventually, we should have one client binary where I select `--testnet` for Sepolia (will replace Goerli) + Bitcoin testnet, and `--developer` for local Ethereum and regtest. Mainnet Ethereum + mainnet Bitcoin would be the default one. Renaming `--goerli` to `--testnet` is the first step. The next step is figuring out the build process (out of scope currently) so that we build one client binary instead of testnet-specific and mainnet-specific versions (out of scope of this PR).

To be done when working on this issue:
- [x] Rename `--goerli` flag to `--testnet` (https://github.com/keep-network/keep-core/pull/3583) https://github.com/keep-network/keep-core/blob/cf266a693b5ad922699039e0fbc15451027c43d3/cmd/flags.go#L86
- [x] Remove `--mainnet` flag https://github.com/keep-network/keep-core/blob/cf266a693b5ad922699039e0fbc15451027c43d3/cmd/flags.go#L78-L79
- [x] Update infrastructure config files (https://github.com/keep-network/keep-core/pull/3604)
- [x] Update config samples and documentation (https://app.gitbook.com/o/R2meumXNNad4y1B10iL7/s/WosjlL4zUGUMlcMfuSAp/~/changes/216)

**Comment by nkuba** [comment]
>     * [ ]  Remove `--mainnet` flag https://github.com/keep-network/keep-core/blob/cf266a693b5ad922699039e0fbc15451027c43d3/cmd/flags.go#L78-L79

We decided to mark the flag deprecated for backward compatibility and remove it in the future. Please see https://github.com/keep-network/keep-core/pull/3583
