### ISSUE TITLE
Mainnet Electrum Servers Monitoring

### ISSUE THREAD

**Issue by nkuba** [keep-network/keep-core#3594]
Currently, integration tests in the client validate integration with testnet electrum servers (see: [pkg/bitcoin/electrum/electrum_integration_test.go](https://github.com/keep-network/keep-core/blob/bfb505ffad9e815cfc493fb12098eafbaab5c5e8/pkg/bitcoin/electrum/electrum_integration_test.go)).
We need a way to validate the mainnet servers we embedded in the client:
- [ ] support all the functions the client uses,
- [ ] are up-to-date with the chain tip.

We need this verification to be executed periodically and alert us in case of discovered problems.

**Comment by pdyraga** [comment]
We agreed with @nkuba to close this issue when #3599 is merged. Electrum connectivity monitoring will be addressed in #3608.
