### ISSUE TITLE
Automate deposit and redemption WalletCoordinator actions

### ISSUE THREAD

**Issue by pdyraga** [keep-network/keep-core#3614]
The [`WalletCoordinator` contract](https://etherscan.io/address/0x64EA4b84e2BdfD313428b96658260E495a420093) is a synchronization point for the network clients. They observe events emitted from this contract and execute the given action previously performing all the required validations of the proposal.

Deposit sweep proposals are currently submitted manually by the dev team. This is possible because sweeps are not as time-sensitive as redemptions but still, we consider it a temporary measure until the proper automation is implemented. 

This issue aims at automating both deposit sweep proposals and redemption proposals in the `WalletCoordinator`. This code should be a part of the existing maintainer module in the client, activated/deactivated based on the config flag.

The logic should be simple for the start: check every 3 hours if there are any redemptions requested. If yes, check if no sweeping is in progress and request redemption of max N deposits. N should be adjustable in the `WalletCoordinator` contract and set based on the gas cost of submitting redemption SPV proof for the given N. 

For the start, sweeps should be proposed every 48 hours if there are no redemptions pending. Given we have optimistic minting, sweeps are not time-sensitive.

When working on this issue please ensure the approach is consistent with SPV proof maintainer module from #3615.

The solution should integrate with redemptions requests implementation from https://github.com/keep-network/keep-core/issues/3609.
```[tasklist]
### Pull Requests
- [ ] https://github.com/keep-network/keep-core/pull/3626
- [ ] https://github.com/keep-network/keep-core/pull/3666
- [ ] https://github.com/keep-network/keep-core/pull/3631
- [ ] https://github.com/keep-network/keep-core/pull/3635
- [ ] https://github.com/keep-network/keep-core/pull/3640
- [ ] https://github.com/keep-network/keep-core/pull/3651
- [ ] https://github.com/keep-network/keep-core/pull/3659
- [ ] https://github.com/keep-network/keep-core/pull/3660
- [ ] https://github.com/keep-network/keep-core/pull/3661
- [ ] https://github.com/keep-network/keep-core/pull/3663
- [ ] https://github.com/keep-network/keep-core/pull/3668
```

**Comment by nkuba** [comment]
> For the start, sweeps should be proposed every 48 hours if there are no redemptions pending. Given we have optimistic minting, sweeps are not time-sensitive.

Would it be worth defining a max number of deposits to sweep in the `WalletCoordinator` contract?
