### ISSUE TITLE
v2.0.0-m4 release (redemptions)

### ISSUE THREAD

**Issue by pdyraga** [keep-network/keep-core#3674]
Team | Address
------------ | -------------
**Threshold Council** | `0x9f6e831c8f8939dc0c830c6e492e7cef4f9c2f5f`

# Outstanding prerequisites
- [x] https://github.com/keep-network/tbtc-v2/issues/641
- [x] https://github.com/keep-network/keep-core/issues/3615
- [x] https://github.com/threshold-network/token-dashboard/issues/553
- [x] User Acceptance Tests completed on Goerli + Bitcoin testnet
- [x] https://github.com/keep-network/keep-core/pull/3689

# Build testnet client

- [x] Build Docker image for testnet
- [x] Publish Docker image for testnet to internal registry
- [x] Update testnet nodes
- [x] Publish Docker image for testnet to public registry

# Tag and build mainnet client
- [x] Tag `v2.0.0-m4`
- [x] Organize PRs and issues into a `v2.0.0-m4` milestone
- [x] Make sure appropriate replace rules are in place
- [x] Build Linux binary
- [x] Install binary on a dev mainnet node, and confirm it works as expected
- [x] Sign Linux binary hash
- [x] Build Docker image
- [x] Sign Docker image hash
- [x] Publish release notes

# Tag and build tbtc-sdk
- [x] Tag `typescript/v1.3.0`
- [x] Sign the commit hash
- [x] Publish the NPM package
- [x]  Publish release notes

# Beta stakers
- [x] Notify beta stakers to update nodes
- [x] Confirm beta stakers updated nodes

# Update maintainer bot
- [x] Authorize Keep Maintainer Bot in the `LightRelayMaintainerProxy`
- [x] Build the new bot image
- [x] Update internal image registry and bot deployment (https://github.com/keep-network/keep-core/pull/3692)
- [x] Make sure all maintainer modes are active (SPV, wallet coordinator, Bitcoin difficulty)

# Tag and build mainnet dashboard
- [x] Prepare `releases/mainnet/v1.9.0` release branch
- [x] Tag `v1.9.0`
- [x] Sign the commit hash
- [x] Organize PRs and issues into a `v1.9.0` milestone
- [x] Deploy dashboard on a mainnet preview

# On-chain setup

Steps executed by Threshold Council:
- [x] Update DKG result submission timeout in `WalletRegistry` contract to `2575`
- [x] Update `walletCreationPeriod` in `Bridge` contract to `1209600`
- [x] Update `walletCreationMaxBtcBalance` in `Bridge` contract to `10000000000`
- [x] Update `redemptionDustThreshold` in `Bridge` contract to `1000000`
- [x] Update `redemptionTimeout` in `Bridge` contract to `3628800`.

Steps executed by Dev Team:
- [x] Request new wallet creation, and wait for DKG to complete

# Mainnet acceptance tests
- [x] User Acceptance Tests completed on Mainnet Threshold Dashboard preview

# Release mainnet dashboard
- [x] Publish mainnet dashboard to prod
- [x] Publish release notes

# Communication
- [x] Publish Discord announcement for all stakers

**Comment by mhluongo** [comment]
Param updates kicked off by the Threshold Council, to be finalized after governance delay

https://etherscan.io/tx/0xd0fc1e3e8a2177def17a5f289985473d3aa53e94910e2ed4db4a70edd9d79e02#eventlog
