### ISSUE TITLE
Improve redemption request proposal event deduplication

### ISSUE THREAD

**Issue by pdyraga** [keep-network/keep-core#3698]
The deduplicator for redemption proposal events takes into account redeemer output script and redemption TX fee:

https://github.com/keep-network/keep-core/blob/c83fc9a6d7b335d9a9fd6a3580c429423f1b03f6/pkg/tbtc/deduplicator.go#L203-L208

If the given redeemer is the only one redeeming for the last few hours and the Bitcoin TX fee estimation did not change, the redemption proposal for the second (valid!) redemption request will be ignored as a duplicate. 

One possible option to fix this could be to shorten the caching period for this particular event. There may be better solutions but I can't think of any right now.

**Comment by erdogan** [comment]
@lukasz-zimnoch, this was opened by Piotr but did not have an owner. Temporarily tagging you here, feel free to reassign or deprioritize if this is not urgent

**Comment by lukasz-zimnoch** [comment]
No longer relevant due to: https://github.com/keep-network/tbtc-v2/issues/737
