### ISSUE TITLE
User acceptance tests of the moving funds mechanism

### ISSUE THREAD

**Issue by lukasz-zimnoch** [keep-network/keep-core#3795]
The scope of this issue includes the design and execution of the user acceptance tests for the client-side of the [moving funds mechanism](https://github.com/keep-network/tbtc-v2/tree/main/docs#wallet-closure) developed recently. UATs should be executed on Sepolia testnet once necessary client and contract upgrades are deployed there.

```[tasklist]
### Tasks
- [x] Design UAT scenarios ([Coda document](https://coda.io/d/Building-Keep_d-fmEgBNFVH/Moving-Funds-UATs_suRIl#_luzja))
- [x] Execute designed UAT scenarios
```

**Comment by michalinacienciala** [comment]
Moving funds UATs executed. Report: https://coda.io/d/Building-Keep_d-fmEgBNFVH/Moving-Funds-UATs_suRIl#_luOJq.
I didn't execute moving funds testing after failed heartbeats, as this functionality is yet not implemented. We'll test this once we have it.
